//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PeriodResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PeriodResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.ContractManagement.PeriodResources", typeof(PeriodResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Term.
        /// </summary>
        public static string AcademicYearTerm {
            get {
                return ResourceManager.GetString("AcademicYearTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Term End Date.
        /// </summary>
        public static string AcademicYearTermEndDate {
            get {
                return ResourceManager.GetString("AcademicYearTermEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Term Period.
        /// </summary>
        public static string AcademicYearTermPeriod {
            get {
                return ResourceManager.GetString("AcademicYearTermPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year Term Start Date.
        /// </summary>
        public static string AcademicYearTermStartDate {
            get {
                return ResourceManager.GetString("AcademicYearTermStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission End Date.
        /// </summary>
        public static string AdmissionEndDate {
            get {
                return ResourceManager.GetString("AdmissionEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission end date must be greater than admission start date.
        /// </summary>
        public static string AdmissionEndDateMustBeGreaterThanAdmissionStartDate {
            get {
                return ResourceManager.GetString("AdmissionEndDateMustBeGreaterThanAdmissionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admission Start Date.
        /// </summary>
        public static string AdmissionStartDate {
            get {
                return ResourceManager.GetString("AdmissionStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be greater than registration start date ..
        /// </summary>
        public static string AdmissionStartDateMustBeGreaterThanRegistrationStartDate {
            get {
                return ResourceManager.GetString("AdmissionStartDateMustBeGreaterThanRegistrationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status End Date.
        /// </summary>
        public static string ChangeStatusEndDate {
            get {
                return ResourceManager.GetString("ChangeStatusEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change status end date end date must be greater than Change status start date.
        /// </summary>
        public static string ChangeStatusEndDateMustBeGreaterThanChangeStatusStartDate {
            get {
                return ResourceManager.GetString("ChangeStatusEndDateMustBeGreaterThanChangeStatusStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status Start Date.
        /// </summary>
        public static string ChangeStatusStartDate {
            get {
                return ResourceManager.GetString("ChangeStatusStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string College {
            get {
                return ResourceManager.GetString("College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleges.
        /// </summary>
        public static string Colleges {
            get {
                return ResourceManager.GetString("Colleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Type.
        /// </summary>
        public static string CollegeType {
            get {
                return ResourceManager.GetString("CollegeType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be greater than academic year term start date ..
        /// </summary>
        public static string DateMustBeGreaterThanAcademicYearTermStartDate {
            get {
                return ResourceManager.GetString("DateMustBeGreaterThanAcademicYearTermStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date must be less than the end date of the academic year term ..
        /// </summary>
        public static string DateMustBeLessThanAcademicYearTermEndDate {
            get {
                return ResourceManager.GetString("DateMustBeLessThanAcademicYearTermEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The date must not exceed two weeks from the academic year term start date.
        /// </summary>
        public static string DateMustBeNotExceedTwoWeeksOfAcademicYearTermStartDate {
            get {
                return ResourceManager.GetString("DateMustBeNotExceedTwoWeeksOfAcademicYearTermStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferral End Date.
        /// </summary>
        public static string DeferralEndDate {
            get {
                return ResourceManager.GetString("DeferralEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferral end date must be greater than deferral start date.
        /// </summary>
        public static string DeferralEndDateMustBeGreaterThanDeferralStartDate {
            get {
                return ResourceManager.GetString("DeferralEndDateMustBeGreaterThanDeferralStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferral Start Date.
        /// </summary>
        public static string DeferralStartDate {
            get {
                return ResourceManager.GetString("DeferralStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissmis End Date.
        /// </summary>
        public static string DissmisEndDate {
            get {
                return ResourceManager.GetString("DissmisEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissmis end date must be greater than dissmis start date.
        /// </summary>
        public static string DissmisEndDateMustBeGreaterThanDissmisStartDate {
            get {
                return ResourceManager.GetString("DissmisEndDateMustBeGreaterThanDissmisStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dissmis Start Date.
        /// </summary>
        public static string DissmisStartDate {
            get {
                return ResourceManager.GetString("DissmisStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Period.
        /// </summary>
        public static string EditPeriod {
            get {
                return ResourceManager.GetString("EditPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam End Date.
        /// </summary>
        public static string ExamEndDate {
            get {
                return ResourceManager.GetString("ExamEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam end date must be greater than exam start date.
        /// </summary>
        public static string ExamEndDateMustBeGreaterThanExamStartDate {
            get {
                return ResourceManager.GetString("ExamEndDateMustBeGreaterThanExamStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Start Date.
        /// </summary>
        public static string ExamStartDate {
            get {
                return ResourceManager.GetString("ExamStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Period.
        /// </summary>
        public static string NewPeriod {
            get {
                return ResourceManager.GetString("NewPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-Show End Date.
        /// </summary>
        public static string NoShowEndDate {
            get {
                return ResourceManager.GetString("NoShowEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-Show end date must be greater than no-show start date.
        /// </summary>
        public static string NoShowEndDateMustBeGreaterThanNoShowStartDate {
            get {
                return ResourceManager.GetString("NoShowEndDateMustBeGreaterThanNoShowStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No-Show Start Date.
        /// </summary>
        public static string NoShowStartDate {
            get {
                return ResourceManager.GetString("NoShowStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Code.
        /// </summary>
        public static string PeriodCode {
            get {
                return ResourceManager.GetString("PeriodCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length {0} should not exceed 10 digits.
        /// </summary>
        public static string PeriodCodeMaxLength {
            get {
                return ResourceManager.GetString("PeriodCodeMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Details.
        /// </summary>
        public static string PeriodDetails {
            get {
                return ResourceManager.GetString("PeriodDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period List.
        /// </summary>
        public static string PeriodList {
            get {
                return ResourceManager.GetString("PeriodList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration End Date.
        /// </summary>
        public static string RegistrationEndDate {
            get {
                return ResourceManager.GetString("RegistrationEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration Start Date.
        /// </summary>
        public static string RegistrationStartDate {
            get {
                return ResourceManager.GetString("RegistrationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration end date must be greater than registration start date.
        /// </summary>
        public static string RegistrationStartDateMustBeGreaterThanRegistrationStartDate {
            get {
                return ResourceManager.GetString("RegistrationStartDateMustBeGreaterThanRegistrationStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renistate End Date.
        /// </summary>
        public static string RenistateEndDate {
            get {
                return ResourceManager.GetString("RenistateEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renistate end date must be greater than renistate start date.
        /// </summary>
        public static string RenistateEndDateMustBeGreaterThanRenistateStartDate {
            get {
                return ResourceManager.GetString("RenistateEndDateMustBeGreaterThanRenistateStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renistate Start Date.
        /// </summary>
        public static string RenistateStartDate {
            get {
                return ResourceManager.GetString("RenistateStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer End Date.
        /// </summary>
        public static string TransferEndDate {
            get {
                return ResourceManager.GetString("TransferEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer end date must be greater than transfer start date.
        /// </summary>
        public static string TransferEndDateMustBeGreaterThanTransferStartDate {
            get {
                return ResourceManager.GetString("TransferEndDateMustBeGreaterThanTransferStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Start Date.
        /// </summary>
        public static string TransferStartDate {
            get {
                return ResourceManager.GetString("TransferStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithDraw End Date.
        /// </summary>
        public static string WithDrawEndDate {
            get {
                return ResourceManager.GetString("WithDrawEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw end date must be greater than withdraw start date.
        /// </summary>
        public static string WithDrawEndDateMustBeGreaterThanWithDrawStartDate {
            get {
                return ResourceManager.GetString("WithDrawEndDateMustBeGreaterThanWithDrawStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WithDraw Start Date.
        /// </summary>
        public static string WithDrawStartDate {
            get {
                return ResourceManager.GetString("WithDrawStartDate", resourceCulture);
            }
        }
    }
}
