//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SponserResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SponserResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.ContractManagement.SponserResources", typeof(SponserResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country.
        /// </summary>
        public static string Country {
            get {
                return ResourceManager.GetString("Country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , You cannot delete this sponser because it is related with other records in college sponser.
        /// </summary>
        public static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Provider.
        /// </summary>
        public static string EditProvider {
            get {
                return ResourceManager.GetString("EditProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Sponsor.
        /// </summary>
        public static string EditSponser {
            get {
                return ResourceManager.GetString("EditSponser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook URL.
        /// </summary>
        public static string FacebookURL {
            get {
                return ResourceManager.GetString("FacebookURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax Number.
        /// </summary>
        public static string FaxNo {
            get {
                return ResourceManager.GetString("FaxNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid email address.
        /// </summary>
        public static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid phone number.
        /// </summary>
        public static string InvalidPhoneNumber {
            get {
                return ResourceManager.GetString("InvalidPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid url.
        /// </summary>
        public static string InvalidUrl {
            get {
                return ResourceManager.GetString("InvalidUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string MobileNo1 {
            get {
                return ResourceManager.GetString("MobileNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Mobile.
        /// </summary>
        public static string MobileNo2 {
            get {
                return ResourceManager.GetString("MobileNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Sponsor.
        /// </summary>
        public static string NewSponser {
            get {
                return ResourceManager.GetString("NewSponser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string OfficialEmail {
            get {
                return ResourceManager.GetString("OfficialEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provider Representive.
        /// </summary>
        public static string ProviderRepresentive {
            get {
                return ResourceManager.GetString("ProviderRepresentive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Email.
        /// </summary>
        public static string RepresentativeEmail {
            get {
                return ResourceManager.GetString("RepresentativeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Job Title.
        /// </summary>
        public static string RepresentativeJobTitle {
            get {
                return ResourceManager.GetString("RepresentativeJobTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Mobile.
        /// </summary>
        public static string RepresentativeMobileNo {
            get {
                return ResourceManager.GetString("RepresentativeMobileNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Representative Name.
        /// </summary>
        public static string RepresentativeName {
            get {
                return ResourceManager.GetString("RepresentativeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Contact.
        /// </summary>
        public static string SponserContact {
            get {
                return ResourceManager.GetString("SponserContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Details.
        /// </summary>
        public static string SponserDetails {
            get {
                return ResourceManager.GetString("SponserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Information.
        /// </summary>
        public static string SponserInfo {
            get {
                return ResourceManager.GetString("SponserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor List.
        /// </summary>
        public static string SponserList {
            get {
                return ResourceManager.GetString("SponserList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sponsor Representive.
        /// </summary>
        public static string SponserRepresentive {
            get {
                return ResourceManager.GetString("SponserRepresentive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status1 {
            get {
                return ResourceManager.GetString("Status1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative  Email.
        /// </summary>
        public static string SupportEmail {
            get {
                return ResourceManager.GetString("SupportEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string TelNo1 {
            get {
                return ResourceManager.GetString("TelNo1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alternative Telephone.
        /// </summary>
        public static string TelNo2 {
            get {
                return ResourceManager.GetString("TelNo2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Twitter URL.
        /// </summary>
        public static string TwitterURL {
            get {
                return ResourceManager.GetString("TwitterURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Web Address.
        /// </summary>
        public static string WebAddress {
            get {
                return ResourceManager.GetString("WebAddress", resourceCulture);
            }
        }
    }
}
