//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExamBookingResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExamBookingResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.Enrollment.ExamBookingResources", typeof(ExamBookingResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Appointment Booking.
        /// </summary>
        public static string AppointmentBooking {
            get {
                return ResourceManager.GetString("AppointmentBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All students already have attendance recorded.
        /// </summary>
        public static string AttendanceRecorded {
            get {
                return ResourceManager.GetString("AttendanceRecorded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Times For The Exam.
        /// </summary>
        public static string AvailableExamTimes {
            get {
                return ResourceManager.GetString("AvailableExamTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking Successful.
        /// </summary>
        public static string BookingRetakeSuccessful {
            get {
                return ResourceManager.GetString("BookingRetakeSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        public static string BookNow {
            get {
                return ResourceManager.GetString("BookNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay the fee.
        /// </summary>
        public static string BookTheFee {
            get {
                return ResourceManager.GetString("BookTheFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A Cancelation Request already Exist.
        /// </summary>
        public static string CancelationRequestExist {
            get {
                return ResourceManager.GetString("CancelationRequestExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Cancelation Request Submitted successfully.
        /// </summary>
        public static string CancelationRequestSubmitted {
            get {
                return ResourceManager.GetString("CancelationRequestSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Canceled.
        /// </summary>
        public static string Canceled {
            get {
                return ResourceManager.GetString("Canceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Expiry Date(MM/YY).
        /// </summary>
        public static string CardExpiryDate {
            get {
                return ResourceManager.GetString("CardExpiryDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Holder Name.
        /// </summary>
        public static string CardHolderName {
            get {
                return ResourceManager.GetString("CardHolderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Number.
        /// </summary>
        public static string CardNumber {
            get {
                return ResourceManager.GetString("CardNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Verification Code (CVC).
        /// </summary>
        public static string CardVerificationCode {
            get {
                return ResourceManager.GetString("CardVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        public static string Center {
            get {
                return ResourceManager.GetString("Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment List.
        /// </summary>
        public static string CommentList {
            get {
                return ResourceManager.GetString("CommentList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed.
        /// </summary>
        public static string Confirmed {
            get {
                return ResourceManager.GetString("Confirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmed Bookings.
        /// </summary>
        public static string ConfirmedBookings {
            get {
                return ResourceManager.GetString("ConfirmedBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelation Invoice.
        /// </summary>
        public static string CreditNoteFile {
            get {
                return ResourceManager.GetString("CreditNoteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can edit your current booking.
        /// </summary>
        public static string EditCurrentBooking {
            get {
                return ResourceManager.GetString("EditCurrentBooking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your exam booking canceled.
        /// </summary>
        public static string EmailCancelationTitle {
            get {
                return ResourceManager.GetString("EmailCancelationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupational safety and health cadres program exam.
        /// </summary>
        public static string EmailTitle {
            get {
                return ResourceManager.GetString("EmailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Cancelled.
        /// </summary>
        public static string EmergencyCancelled {
            get {
                return ResourceManager.GetString("EmergencyCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Booking Details.
        /// </summary>
        public static string ExamBookingDetails {
            get {
                return ResourceManager.GetString("ExamBookingDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Center Details.
        /// </summary>
        public static string ExamCenterDetails {
            get {
                return ResourceManager.GetString("ExamCenterDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam City.
        /// </summary>
        public static string ExamCity {
            get {
                return ResourceManager.GetString("ExamCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Code.
        /// </summary>
        public static string ExamCode {
            get {
                return ResourceManager.GetString("ExamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Date.
        /// </summary>
        public static string ExamDate {
            get {
                return ResourceManager.GetString("ExamDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Detail.
        /// </summary>
        public static string ExamDetail {
            get {
                return ResourceManager.GetString("ExamDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Location Url.
        /// </summary>
        public static string ExameCenterLocationUrl {
            get {
                return ResourceManager.GetString("ExameCenterLocationUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Name.
        /// </summary>
        public static string ExameCenterName {
            get {
                return ResourceManager.GetString("ExameCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam End At.
        /// </summary>
        public static string ExamEndAt {
            get {
                return ResourceManager.GetString("ExamEndAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam fee payment.
        /// </summary>
        public static string ExamFees {
            get {
                return ResourceManager.GetString("ExamFees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Language.
        /// </summary>
        public static string ExamLanguage {
            get {
                return ResourceManager.GetString("ExamLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Name.
        /// </summary>
        public static string ExamName {
            get {
                return ResourceManager.GetString("ExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Payment Details.
        /// </summary>
        public static string ExamPaymentDetails {
            get {
                return ResourceManager.GetString("ExamPaymentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Result.
        /// </summary>
        public static string ExamResult {
            get {
                return ResourceManager.GetString("ExamResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Start At.
        /// </summary>
        public static string ExamStartAt {
            get {
                return ResourceManager.GetString("ExamStartAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam URL.
        /// </summary>
        public static string ExamURL {
            get {
                return ResourceManager.GetString("ExamURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail.
        /// </summary>
        public static string Fail {
            get {
                return ResourceManager.GetString("Fail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Invoice .
        /// </summary>
        public static string InvoiceFile {
            get {
                return ResourceManager.GetString("InvoiceFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment and refunds invoices .
        /// </summary>
        public static string Invoices {
            get {
                return ResourceManager.GetString("Invoices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invoice Type.
        /// </summary>
        public static string InvoiceType {
            get {
                return ResourceManager.GetString("InvoiceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledgment of &lt;a href=&quot;/ExamBooking/PayAndRefundPolicy&quot; target=&quot;_blank&quot;&gt;the payment and refund policy &lt;/a&gt;.
        /// </summary>
        public static string IsAgreeOnPayPolicy {
            get {
                return ResourceManager.GetString("IsAgreeOnPayPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested before.
        /// </summary>
        public static string IsRequestedRefund {
            get {
                return ResourceManager.GetString("IsRequestedRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot cancel according to the payment and refund policies.
        /// </summary>
        public static string Msg_CannotCancel {
            get {
                return ResourceManager.GetString("Msg_CannotCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot refund selected payment.
        /// </summary>
        public static string Msg_CannotRefund {
            get {
                return ResourceManager.GetString("Msg_CannotRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exam booking is canceled and the exam fees are not refunded please contact the administrator.
        /// </summary>
        public static string MsgCanceledWithoutRefunded {
            get {
                return ResourceManager.GetString("MsgCanceledWithoutRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The exam booking is canceled and exam fees refunded.
        /// </summary>
        public static string MsgCanceledWithRefunded {
            get {
                return ResourceManager.GetString("MsgCanceledWithRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fees successfully refunded.
        /// </summary>
        public static string MsgRequestedAndRefunded {
            get {
                return ResourceManager.GetString("MsgRequestedAndRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot refund the fees, please contact the administrator..
        /// </summary>
        public static string MsgRequestedWithoutRefund {
            get {
                return ResourceManager.GetString("MsgRequestedWithoutRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must agree on the Pay And Refund Policy.
        /// </summary>
        public static string MustAgreeOnPayPolicy {
            get {
                return ResourceManager.GetString("MustAgreeOnPayPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are currently no available dates for the exam.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Refunded.
        /// </summary>
        public static string NotRefunded {
            get {
                return ResourceManager.GetString("NotRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can request.
        /// </summary>
        public static string NotRequestedRefund {
            get {
                return ResourceManager.GetString("NotRequestedRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Bookings.
        /// </summary>
        public static string OpenBookings {
            get {
                return ResourceManager.GetString("OpenBookings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paid Amount.
        /// </summary>
        public static string PaidAmount {
            get {
                return ResourceManager.GetString("PaidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pass.
        /// </summary>
        public static string Pass {
            get {
                return ResourceManager.GetString("Pass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay again and book the exam.
        /// </summary>
        public static string PayAgain {
            get {
                return ResourceManager.GetString("PayAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay And Refund Policy.
        /// </summary>
        public static string PayAndRefundPolicy {
            get {
                return ResourceManager.GetString("PayAndRefundPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The payment received.the schedule is under processing.
        /// </summary>
        public static string PaymentConfirmed {
            get {
                return ResourceManager.GetString("PaymentConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Information.
        /// </summary>
        public static string PaymentInformation {
            get {
                return ResourceManager.GetString("PaymentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Service has an Issue, please try again later.
        /// </summary>
        public static string PaymentServiceIssue {
            get {
                return ResourceManager.GetString("PaymentServiceIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Successful.
        /// </summary>
        public static string PaymentSuccessful {
            get {
                return ResourceManager.GetString("PaymentSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment and refund policy link.
        /// </summary>
        public static string PayPolicyLink {
            get {
                return ResourceManager.GetString("PayPolicyLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string Pending {
            get {
                return ResourceManager.GetString("Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending result.
        /// </summary>
        public static string PendingResult {
            get {
                return ResourceManager.GetString("PendingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string Qualification {
            get {
                return ResourceManager.GetString("Qualification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded.
        /// </summary>
        public static string Refunded {
            get {
                return ResourceManager.GetString("Refunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refunded Credits.
        /// </summary>
        public static string RefundedCredits {
            get {
                return ResourceManager.GetString("RefundedCredits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requested Refund.
        /// </summary>
        public static string RequestedRefund {
            get {
                return ResourceManager.GetString("RequestedRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request a Refund.
        /// </summary>
        public static string RequestRefund {
            get {
                return ResourceManager.GetString("RequestRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reschedual.
        /// </summary>
        public static string Reschedual {
            get {
                return ResourceManager.GetString("Reschedual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result.
        /// </summary>
        public static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retake The Exam.
        /// </summary>
        public static string ReTakeExam {
            get {
                return ResourceManager.GetString("ReTakeExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SARAS Confirmed.
        /// </summary>
        public static string SARASConfirmed {
            get {
                return ResourceManager.GetString("SARASConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected slot is currently unavailable, Please select another exam slot..
        /// </summary>
        public static string SlotUnavailable {
            get {
                return ResourceManager.GetString("SlotUnavailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The selected slot is currently unavailable, And exam fees was Refunded, Please select another exam slot..
        /// </summary>
        public static string SlotUnavailableAndfeesRefunded {
            get {
                return ResourceManager.GetString("SlotUnavailableAndfeesRefunded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful Refund.
        /// </summary>
        public static string SuccessfulRefund {
            get {
                return ResourceManager.GetString("SuccessfulRefund", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Information.
        /// </summary>
        public static string TraineeInformation {
            get {
                return ResourceManager.GetString("TraineeInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string TraineeName {
            get {
                return ResourceManager.GetString("TraineeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student NationalID.
        /// </summary>
        public static string TraineeNationalID {
            get {
                return ResourceManager.GetString("TraineeNationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work is underway to add test centers in other regions.
        /// </summary>
        public static string UnavailableCity {
            get {
                return ResourceManager.GetString("UnavailableCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upcoming Bookings.
        /// </summary>
        public static string UpcomingBookings {
            get {
                return ResourceManager.GetString("UpcomingBookings", resourceCulture);
            }
        }
    }
}
