//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization.Security {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SecurityResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SecurityResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.Security.SecurityResources", typeof(SecurityResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleges.
        /// </summary>
        public static string Action_UserColleges {
            get {
                return ResourceManager.GetString("Action_UserColleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Details.
        /// </summary>
        public static string Action_UserDetails {
            get {
                return ResourceManager.GetString("Action_UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications.
        /// </summary>
        public static string Action_UserQualifications {
            get {
                return ResourceManager.GetString("Action_UserQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Action_UserRoles {
            get {
                return ResourceManager.GetString("Action_UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Deleted Successfully.
        /// </summary>
        public static string ActionDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("ActionDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Name.
        /// </summary>
        public static string ActionName {
            get {
                return ResourceManager.GetString("ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Saved Successfully.
        /// </summary>
        public static string ActionSavedSuccessMessage {
            get {
                return ResourceManager.GetString("ActionSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions  Saved Successfully.
        /// </summary>
        public static string ActionsSavedSuccessMessage {
            get {
                return ResourceManager.GetString("ActionsSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Updated Successfully.
        /// </summary>
        public static string ActionUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("ActionUpdatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Directory.
        /// </summary>
        public static string ActiveDirectoryUser {
            get {
                return ResourceManager.GetString("ActiveDirectoryUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Action.
        /// </summary>
        public static string AddAction {
            get {
                return ResourceManager.GetString("AddAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Actions.
        /// </summary>
        public static string AddActions {
            get {
                return ResourceManager.GetString("AddActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add College.
        /// </summary>
        public static string AddCollege {
            get {
                return ResourceManager.GetString("AddCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add College Staff.
        /// </summary>
        public static string AddCollegeStaff {
            get {
                return ResourceManager.GetString("AddCollegeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Successfully.
        /// </summary>
        public static string AddedSuccessfully {
            get {
                return ResourceManager.GetString("AddedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Module.
        /// </summary>
        public static string AddModule {
            get {
                return ResourceManager.GetString("AddModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Module Action.
        /// </summary>
        public static string AddModuleAction {
            get {
                return ResourceManager.GetString("AddModuleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Module Category.
        /// </summary>
        public static string AddModuleCategory {
            get {
                return ResourceManager.GetString("AddModuleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Power Role.
        /// </summary>
        public static string AddPowerRole {
            get {
                return ResourceManager.GetString("AddPowerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Role.
        /// </summary>
        public static string AddRole {
            get {
                return ResourceManager.GetString("AddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title *.
        /// </summary>
        public static string AdminTitle {
            get {
                return ResourceManager.GetString("AdminTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string AlertHeader {
            get {
                return ResourceManager.GetString("AlertHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string Alertsuccess {
            get {
                return ResourceManager.GetString("Alertsuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in change password , make sure you entred correct password.
        /// </summary>
        public static string ChangePasswordInvalidMsg {
            get {
                return ResourceManager.GetString("ChangePasswordInvalidMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleges.
        /// </summary>
        public static string College {
            get {
                return ResourceManager.GetString("College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string College_Name {
            get {
                return ResourceManager.GetString("College_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Arabic Name.
        /// </summary>
        public static string College_NameAr {
            get {
                return ResourceManager.GetString("College_NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string CollegeID {
            get {
                return ResourceManager.GetString("CollegeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Name.
        /// </summary>
        public static string CollegeName {
            get {
                return ResourceManager.GetString("CollegeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Colleges Saved Successfully.
        /// </summary>
        public static string CollegeSavedSuccessMessage {
            get {
                return ResourceManager.GetString("CollegeSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Staff.
        /// </summary>
        public static string CollegeStaff {
            get {
                return ResourceManager.GetString("CollegeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Staff.
        /// </summary>
        public static string CreateCollegeStaff {
            get {
                return ResourceManager.GetString("CreateCollegeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created By.
        /// </summary>
        public static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create User.
        /// </summary>
        public static string CreateUser {
            get {
                return ResourceManager.GetString("CreateUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to create with this staff member data.
        /// </summary>
        public static string CreateUserConfirm {
            get {
                return ResourceManager.GetString("CreateUserConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Deactivated.
        /// </summary>
        public static string DeactivateSuccess {
            get {
                return ResourceManager.GetString("DeactivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string DefaultSelect {
            get {
                return ResourceManager.GetString("DefaultSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are about to delete item permanently. Are you sure you want to delete this item?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Name.
        /// </summary>
        public static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Action.
        /// </summary>
        public static string EdidAction {
            get {
                return ResourceManager.GetString("EdidAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit  Module Action.
        /// </summary>
        public static string EdidModuleAction {
            get {
                return ResourceManager.GetString("EdidModuleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit College.
        /// </summary>
        public static string EditCollege {
            get {
                return ResourceManager.GetString("EditCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Staff.
        /// </summary>
        public static string EditCollegeStaff {
            get {
                return ResourceManager.GetString("EditCollegeStaff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Module.
        /// </summary>
        public static string EditModule {
            get {
                return ResourceManager.GetString("EditModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Module Category.
        /// </summary>
        public static string EditModuleCategory {
            get {
                return ResourceManager.GetString("EditModuleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Power Role.
        /// </summary>
        public static string EditPowerRole {
            get {
                return ResourceManager.GetString("EditPowerRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Qualifications.
        /// </summary>
        public static string EditQualifications {
            get {
                return ResourceManager.GetString("EditQualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Role.
        /// </summary>
        public static string EditRole {
            get {
                return ResourceManager.GetString("EditRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string EditUser {
            get {
                return ResourceManager.GetString("EditUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effective Date.
        /// </summary>
        public static string EffectiveDate {
            get {
                return ResourceManager.GetString("EffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Already Registered.
        /// </summary>
        public static string EmailAlreadyRegistered {
            get {
                return ResourceManager.GetString("EmailAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ---.
        /// </summary>
        public static string EmptyValue {
            get {
                return ResourceManager.GetString("EmptyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in deleting {0}.
        /// </summary>
        public static string ErrorMessageCannotDelete {
            get {
                return ResourceManager.GetString("ErrorMessageCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Action is related to other data.
        /// </summary>
        public static string ErrorMessageRelatedDataAction {
            get {
                return ResourceManager.GetString("ErrorMessageRelatedDataAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module category is related to other data.
        /// </summary>
        public static string ErrorMessageRelatedDataMCategory {
            get {
                return ResourceManager.GetString("ErrorMessageRelatedDataMCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This module is related to other data.
        /// </summary>
        public static string ErrorMessageRelatedDataModule {
            get {
                return ResourceManager.GetString("ErrorMessageRelatedDataModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This role is related to other data.
        /// </summary>
        public static string ErrorMessageRelatedDataRole {
            get {
                return ResourceManager.GetString("ErrorMessageRelatedDataRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured .
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string FullName {
            get {
                return ResourceManager.GetString("FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Activated Successfully.
        /// </summary>
        public static string ItemActivatedSuccessMessage {
            get {
                return ResourceManager.GetString("ItemActivatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item Deactivated Successfully.
        /// </summary>
        public static string ItemDeactivatedSuccessMessage {
            get {
                return ResourceManager.GetString("ItemDeactivatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string JobTypeID {
            get {
                return ResourceManager.GetString("JobTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Qualification Date.
        /// </summary>
        public static string LastQualificationDate {
            get {
                return ResourceManager.GetString("LastQualificationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last qualification date must be less than or equal today.
        /// </summary>
        public static string LastQualificationDateMustBeLessThanToday {
            get {
                return ResourceManager.GetString("LastQualificationDateMustBeLessThanToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Date.
        /// </summary>
        public static string LeaveDate {
            get {
                return ResourceManager.GetString("LeaveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Date Must Be Greater Than Effective Date.
        /// </summary>
        public static string LeaveDateMustBeGreaterThanEffectiveDate {
            get {
                return ResourceManager.GetString("LeaveDateMustBeGreaterThanEffectiveDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave Reason.
        /// </summary>
        public static string LeaveReasonID {
            get {
                return ResourceManager.GetString("LeaveReasonID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string LevelID {
            get {
                return ResourceManager.GetString("LevelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Name.
        /// </summary>
        public static string LoginName {
            get {
                return ResourceManager.GetString("LoginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Category Deleted Successfully.
        /// </summary>
        public static string MCategoryDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("MCategoryDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Category Saved Successfully.
        /// </summary>
        public static string MCategorySavedSuccessMessage {
            get {
                return ResourceManager.GetString("MCategorySavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Permissions.
        /// </summary>
        public static string MenuItem_RoleActions {
            get {
                return ResourceManager.GetString("MenuItem_RoleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string MenuItem_Roles {
            get {
                return ResourceManager.GetString("MenuItem_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        public static string MenuItem_Users {
            get {
                return ResourceManager.GetString("MenuItem_Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module.
        /// </summary>
        public static string Module {
            get {
                return ResourceManager.GetString("Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Action.
        /// </summary>
        public static string ModuleAction {
            get {
                return ResourceManager.GetString("ModuleAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Action Deleted Successfully.
        /// </summary>
        public static string ModuleActionDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("ModuleActionDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Actions.
        /// </summary>
        public static string ModuleActions {
            get {
                return ResourceManager.GetString("ModuleActions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Action Saved Successfully.
        /// </summary>
        public static string ModuleActionSavedSuccessMessage {
            get {
                return ResourceManager.GetString("ModuleActionSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Categories.
        /// </summary>
        public static string ModuleCategories {
            get {
                return ResourceManager.GetString("ModuleCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Category.
        /// </summary>
        public static string ModuleCategory {
            get {
                return ResourceManager.GetString("ModuleCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Category.
        /// </summary>
        public static string ModuleCategoryID {
            get {
                return ResourceManager.GetString("ModuleCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Category Name.
        /// </summary>
        public static string ModuleCategoryName {
            get {
                return ResourceManager.GetString("ModuleCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Deleted Successfully.
        /// </summary>
        public static string ModuleDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("ModuleDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Name.
        /// </summary>
        public static string ModuleName {
            get {
                return ResourceManager.GetString("ModuleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modules.
        /// </summary>
        public static string Modules {
            get {
                return ResourceManager.GetString("Modules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Module Saved Successfully.
        /// </summary>
        public static string ModuleSavedSuccessMessage {
            get {
                return ResourceManager.GetString("ModuleSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nationality.
        /// </summary>
        public static string Nationality {
            get {
                return ResourceManager.GetString("Nationality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The user should have at least one role..
        /// </summary>
        public static string OneRoleMustBeSelected {
            get {
                return ResourceManager.GetString("OneRoleMustBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online.
        /// </summary>
        public static string OnlineUser {
            get {
                return ResourceManager.GetString("OnlineUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Successfully.
        /// </summary>
        public static string PasswordChangedMsg {
            get {
                return ResourceManager.GetString("PasswordChangedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions.
        /// </summary>
        public static string Permissions {
            get {
                return ResourceManager.GetString("Permissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        public static string Phone {
            get {
                return ResourceManager.GetString("Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Already Registered.
        /// </summary>
        public static string PhoneNumberAlreadyRegistered {
            get {
                return ResourceManager.GetString("PhoneNumberAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please add colleges to user.
        /// </summary>
        public static string PleaseAddCollegesToUser {
            get {
                return ResourceManager.GetString("PleaseAddCollegesToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Power Roles.
        /// </summary>
        public static string PowerRoles {
            get {
                return ResourceManager.GetString("PowerRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification.
        /// </summary>
        public static string QualificationID {
            get {
                return ResourceManager.GetString("QualificationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Name.
        /// </summary>
        public static string QualificationName {
            get {
                return ResourceManager.GetString("QualificationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualif.
        /// </summary>
        public static string Qualifications {
            get {
                return ResourceManager.GetString("Qualifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualifications Saved Successfully.
        /// </summary>
        public static string QualificationSavedSuccessMessage {
            get {
                return ResourceManager.GetString("QualificationSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permissions Saved Successfully.
        /// </summary>
        public static string RoleActionsSavedSuccessMessage {
            get {
                return ResourceManager.GetString("RoleActionsSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Deleted Successfully.
        /// </summary>
        public static string RoleDeleteSuccessMessage {
            get {
                return ResourceManager.GetString("RoleDeleteSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dublicate Role Name Or Role Code.
        /// </summary>
        public static string RoleDublicateMessage {
            get {
                return ResourceManager.GetString("RoleDublicateMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Name.
        /// </summary>
        public static string RoleName {
            get {
                return ResourceManager.GetString("RoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role Saved Successfully.
        /// </summary>
        public static string RoleSavedSuccessMessage {
            get {
                return ResourceManager.GetString("RoleSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles Management.
        /// </summary>
        public static string RolesManagement {
            get {
                return ResourceManager.GetString("RolesManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Users.
        /// </summary>
        public static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security Managment.
        /// </summary>
        public static string SecurityManagment {
            get {
                return ResourceManager.GetString("SecurityManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select at least 1 college.
        /// </summary>
        public static string SelectCollegeMsg {
            get {
                return ResourceManager.GetString("SelectCollegeMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Permissions.
        /// </summary>
        public static string SelectModuleCategoryMsg {
            get {
                return ResourceManager.GetString("SelectModuleCategoryMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select Role.
        /// </summary>
        public static string SelectRoleMsg {
            get {
                return ResourceManager.GetString("SelectRoleMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Major.
        /// </summary>
        public static string SpesializationID {
            get {
                return ResourceManager.GetString("SpesializationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Staff {
            get {
                return ResourceManager.GetString("Staff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Managment.
        /// </summary>
        public static string StaffManagment {
            get {
                return ResourceManager.GetString("StaffManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member Deleted Successfully.
        /// </summary>
        public static string StaffMemberDeletedSuccessMessage {
            get {
                return ResourceManager.GetString("StaffMemberDeletedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member Saved Successfully , Username and password sent by email.
        /// </summary>
        public static string StaffMemberSavedSuccessMessage {
            get {
                return ResourceManager.GetString("StaffMemberSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Member Updated Successfully.
        /// </summary>
        public static string StaffMemberUpdatedSuccessMessage {
            get {
                return ResourceManager.GetString("StaffMemberUpdatedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Security.
        /// </summary>
        public static string System_Header {
            get {
                return ResourceManager.GetString("System_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Role.
        /// </summary>
        public static string Title_CreateRole {
            get {
                return ResourceManager.GetString("Title_CreateRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        public static string Title_Roles {
            get {
                return ResourceManager.GetString("Title_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Type.
        /// </summary>
        public static string TypeID {
            get {
                return ResourceManager.GetString("TypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Already Registred.
        /// </summary>
        public static string UserAlreadyRegistred {
            get {
                return ResourceManager.GetString("UserAlreadyRegistred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff member created as user.
        /// </summary>
        public static string UserCreated {
            get {
                return ResourceManager.GetString("UserCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully , please assign roles.
        /// </summary>
        public static string UserCreatedWithAddRoleNotification {
            get {
                return ResourceManager.GetString("UserCreatedWithAddRoleNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string UserDetails {
            get {
                return ResourceManager.GetString("UserDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name Already Registered.
        /// </summary>
        public static string UserNameAlreadyRegistered {
            get {
                return ResourceManager.GetString("UserNameAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not exist or locked in active directory.
        /// </summary>
        public static string UserNotExist {
            get {
                return ResourceManager.GetString("UserNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Roles.
        /// </summary>
        public static string UserRoles {
            get {
                return ResourceManager.GetString("UserRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Saved Successfully.
        /// </summary>
        public static string UserSavedSuccessMessage {
            get {
                return ResourceManager.GetString("UserSavedSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visa / Type.
        /// </summary>
        public static string VisaType {
            get {
                return ResourceManager.GetString("VisaType", resourceCulture);
            }
        }
    }
}
