//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExamRequestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExamRequestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.RPL.ExamRequestResources", typeof(ExamRequestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Record.
        /// </summary>
        public static string AcademicRecord {
            get {
                return ResourceManager.GetString("AcademicRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I accept the terms.
        /// </summary>
        public static string AcceptTermOfService {
            get {
                return ResourceManager.GetString("AcceptTermOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Exam.
        /// </summary>
        public static string ApplyExam {
            get {
                return ResourceManager.GetString("ApplyExam", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve.
        /// </summary>
        public static string Approve {
            get {
                return ResourceManager.GetString("Approve", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Year.
        /// </summary>
        public static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booking.
        /// </summary>
        public static string Booking {
            get {
                return ResourceManager.GetString("Booking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirmation {
            get {
                return ResourceManager.GetString("Confirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational Equation.
        /// </summary>
        public static string EducationalEquation {
            get {
                return ResourceManager.GetString("EducationalEquation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam request approved.
        /// </summary>
        public static string EmailSubjectApproved {
            get {
                return ResourceManager.GetString("EmailSubjectApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam request rejected.
        /// </summary>
        public static string EmailSubjectRejected {
            get {
                return ResourceManager.GetString("EmailSubjectRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam request resent.
        /// </summary>
        public static string EmailSubjectResend {
            get {
                return ResourceManager.GetString("EmailSubjectResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-training attendance certificate.
        /// </summary>
        public static string ETrainingAttendance {
            get {
                return ResourceManager.GetString("ETrainingAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Certificate.
        /// </summary>
        public static string GraduationCertificate {
            get {
                return ResourceManager.GetString("GraduationCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation certificate.
        /// </summary>
        public static string GraduationCertificateAttachments {
            get {
                return ResourceManager.GetString("GraduationCertificateAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to have a health specialization.
        /// </summary>
        public static string HealthSpecialist {
            get {
                return ResourceManager.GetString("HealthSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests list.
        /// </summary>
        public static string IndexTitle {
            get {
                return ResourceManager.GetString("IndexTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I acknowledge that I have completed the e-training.
        /// </summary>
        public static string IseTrainingCompleted {
            get {
                return ResourceManager.GetString("IseTrainingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you have a health specialization?.
        /// </summary>
        public static string IsHealthSpecialist {
            get {
                return ResourceManager.GetString("IsHealthSpecialist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letter of introduction from the employer / experience certificate.
        /// </summary>
        public static string LetterOrexperienceCertificate {
            get {
                return ResourceManager.GetString("LetterOrexperienceCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exam Request.
        /// </summary>
        public static string ModuleTitle {
            get {
                return ResourceManager.GetString("ModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you do not have a certificate of conformity of qualifications and experience from occupational safety and health cadres.
        /// </summary>
        public static string Msg_NotRPL {
            get {
                return ResourceManager.GetString("Msg_NotRPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining the qualification from.
        /// </summary>
        public static string QualificationFrom {
            get {
                return ResourceManager.GetString("QualificationFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inside the kingdom.
        /// </summary>
        public static string QualificationFromInside {
            get {
                return ResourceManager.GetString("QualificationFromInside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Obtaining the qualification from Inside the kingdom.
        /// </summary>
        public static string QualificationFromInsideKSA {
            get {
                return ResourceManager.GetString("QualificationFromInsideKSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside the kingdom.
        /// </summary>
        public static string QualificationFromOutside {
            get {
                return ResourceManager.GetString("QualificationFromOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string RequiredAttachments {
            get {
                return ResourceManager.GetString("RequiredAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saudi council of engineers certificate.
        /// </summary>
        public static string SaudiCouncilOfEngineersCertificate {
            get {
                return ResourceManager.GetString("SaudiCouncilOfEngineersCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to health specialties authority certificate.
        /// </summary>
        public static string SaudiHealthSpecializationsAuthorityCertificate {
            get {
                return ResourceManager.GetString("SaudiHealthSpecializationsAuthorityCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student identity.
        /// </summary>
        public static string StudentIdentity {
            get {
                return ResourceManager.GetString("StudentIdentity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID Attached.
        /// </summary>
        public static string StudentIdentityAttachment {
            get {
                return ResourceManager.GetString("StudentIdentityAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Info.
        /// </summary>
        public static string StudentInfo {
            get {
                return ResourceManager.GetString("StudentInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit a new exam request for e-training students.
        /// </summary>
        public static string SubmitETrainningStudents {
            get {
                return ResourceManager.GetString("SubmitETrainningStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application will be reviewed and the applicant informed of the eligibility to register for the test within a period not exceeding 15 working days..
        /// </summary>
        public static string SubmitMsg {
            get {
                return ResourceManager.GetString("SubmitMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions.
        /// </summary>
        public static string TermsConditions {
            get {
                return ResourceManager.GetString("TermsConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Track.
        /// </summary>
        public static string TrainingTrack {
            get {
                return ResourceManager.GetString("TrainingTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Practitioner.
        /// </summary>
        public static string TrainingTrackPractitioner {
            get {
                return ResourceManager.GetString("TrainingTrackPractitioner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string TrainingTrackProfessional {
            get {
                return ResourceManager.GetString("TrainingTrackProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Years of Experience.
        /// </summary>
        public static string YearsOfExperience {
            get {
                return ResourceManager.GetString("YearsOfExperience", resourceCulture);
            }
        }
    }
}
