//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class AcademicYearTerm
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public AcademicYearTerm()
        {
            this.TermCourse = new HashSet<TermCourse>();
            this.DeferralRequestAcademicYearTerm = new HashSet<DeferralRequestAcademicYearTerm>();
            this.DismissRequest = new HashSet<DismissRequest>();
            this.EnglishExamResult = new HashSet<EnglishExamResult>();
            this.EnrollmentStatistic = new HashSet<EnrollmentStatistic>();
            this.TermEnrollmentStatisticSetting = new HashSet<TermEnrollmentStatisticSetting>();
            this.TransferRequest = new HashSet<TransferRequest>();
            this.UploadRequestDetailsAttendance = new HashSet<UploadRequestDetailsAttendance>();
            this.UploadRequestDetailsSection = new HashSet<UploadRequestDetailsSection>();
            this.UploadRequestDetailsSectionEnrollment = new HashSet<UploadRequestDetailsSectionEnrollment>();
            this.VocationalExamResult = new HashSet<VocationalExamResult>();
            this.WithdrawRequest = new HashSet<WithdrawRequest>();
            this.EnrollmentChangeStatusRequest = new HashSet<EnrollmentChangeStatusRequest>();
            this.CollegePayment = new HashSet<CollegePayment>();
            this.Period = new HashSet<Period>();
            this.PaymentSetting = new HashSet<PaymentSetting>();
            this.ReinstateRequest = new HashSet<ReinstateRequest>();
            this.CollegeAcademicYearTermPeriod = new HashSet<CollegeAcademicYearTermPeriod>();
            this.ContractTermPaymentSetting = new HashSet<ContractTermPaymentSetting>();
            this.AcademicYearTermPeriod = new HashSet<AcademicYearTermPeriod>();
            this.TermEnrollment = new HashSet<TermEnrollment>();
            this.Batch = new HashSet<Batch>();
            this.Batch1 = new HashSet<Batch>();
            this.BatchServicePeriod = new HashSet<BatchServicePeriod>();
            this.CollegeSpecializationRequest = new HashSet<CollegeSpecializationRequest>();
            this.CollegeSpecializationRequest1 = new HashSet<CollegeSpecializationRequest>();
            this.CollegeSpecialization = new HashSet<CollegeSpecialization>();
            this.CollegeSpecialization1 = new HashSet<CollegeSpecialization>();
            this.AssessmentPeriod = new HashSet<AssessmentPeriod>();
            this.StudentGradeBook = new HashSet<StudentGradeBook>();
            this.QualificationPeriod = new HashSet<QualificationPeriod>();
            this.TransferVistorRequest = new HashSet<TransferVistorRequest>();
            this.ComplaintPeriods = new HashSet<ComplaintPeriod>();
        }
    
        public int ID { get; set; }
        public int AcademicYearID { get; set; }
        public int TermTypeID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int TermOrdering { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual TermType TermType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermCourse> TermCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeferralRequestAcademicYearTerm> DeferralRequestAcademicYearTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DismissRequest> DismissRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnglishExamResult> EnglishExamResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentStatistic> EnrollmentStatistic { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermEnrollmentStatisticSetting> TermEnrollmentStatisticSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRequest> TransferRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadRequestDetailsAttendance> UploadRequestDetailsAttendance { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadRequestDetailsSection> UploadRequestDetailsSection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UploadRequestDetailsSectionEnrollment> UploadRequestDetailsSectionEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocationalExamResult> VocationalExamResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WithdrawRequest> WithdrawRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EnrollmentChangeStatusRequest> EnrollmentChangeStatusRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegePayment> CollegePayment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Period> Period { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentSetting> PaymentSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReinstateRequest> ReinstateRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeAcademicYearTermPeriod> CollegeAcademicYearTermPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTermPaymentSetting> ContractTermPaymentSetting { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AcademicYearTermPeriod> AcademicYearTermPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermEnrollment> TermEnrollment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Batch> Batch1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BatchServicePeriod> BatchServicePeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeSpecializationRequest> CollegeSpecializationRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeSpecializationRequest> CollegeSpecializationRequest1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeSpecialization> CollegeSpecialization { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegeSpecialization> CollegeSpecialization1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AssessmentPeriod> AssessmentPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGradeBook> StudentGradeBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QualificationPeriod> QualificationPeriod { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferVistorRequest> TransferVistorRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ComplaintPeriod> ComplaintPeriods { get; set; }
    }
}
