//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class Attachments
    { 
        public System.Guid Id { get; set; }
        public string Name { get; set; }
        public string Extention { get; set; }
        public string Description { get; set; }
        public string ContentType { get; set; }
        public string FilePath { get; set; }
        public int AttachmentTypeId { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AttachmentContents AttachmentContents { get; set; }
        public virtual AttachmentTypes AttachmentTypes { get; set; }
    }
}
