//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class AttachmentContents
    { 
        public System.Guid AttachmentId { get; set; }
        public byte[] Content { get; set; }
    
        public virtual Attachments Attachments { get; set; }
    }
}
