//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class CardsFeedbackValidation
    { 
        public int ID { get; set; }
        public int UploadRequestID { get; set; }
        public string TVTCStudentNo { get; set; }
        public string FullName { get; set; }
        public string NationalID { get; set; }
        public string HijriDate { get; set; }
        public string ArabicFirstName { get; set; }
        public string ArabicSecondName { get; set; }
        public string ArabicFourthName { get; set; }
        public string S { get; set; }
        public string Gender { get; set; }
        public string StaticNo { get; set; }
        public string Reply { get; set; }
        public string CardNo { get; set; }
        public string BankAccountNumber { get; set; }
        public int UploadRejectionReasonID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual UploadRequest UploadRequest { get; set; }
        public virtual UploadRejectionReason UploadRejectionReason { get; set; }
    }
}
