//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class CenterStaff
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CenterStaff()
        {
            this.CenterStaffAttachment = new HashSet<CenterStaffAttachment>();
        }
    
        public int ID { get; set; }
        public int CollegeID { get; set; }
        public string StaffName { get; set; }
        public string EmployabilityLevel { get; set; }
        public string EducationExperience { get; set; }
        public int YearsofEducationExperience { get; set; }
        public string QualificationLevel { get; set; }
        public string TeachingExperienceSector { get; set; }
        public string ManagedUnits { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual College College { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CenterStaffAttachment> CenterStaffAttachment { get; set; }
    }
}
