//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class CenterTrainingCourse
    { 
        public int ID { get; set; }
        public int CollegeID { get; set; }
        public int CityID { get; set; }
        public bool Male { get; set; }
        public bool Female { get; set; }
        public int NumberofTeachers { get; set; }
        public int NumberodTrainees { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual City City { get; set; }
        public virtual College College { get; set; }
    }
}
