//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class CollegePayment
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CollegePayment()
        {
            this.StudentCoursePayment = new HashSet<StudentCoursePayment>();
            this.InvoiceRequest = new HashSet<InvoiceRequest>();
            this.CollegePaymentAttachement = new HashSet<CollegePaymentAttachement>();
            this.StudentMonthlyPayment = new HashSet<StudentMonthlyPayment>();
        }
    
        public int ID { get; set; }
        public int PaymentRequestID { get; set; }
        public int PaymentRequestStatusID { get; set; }
        public int CollegeID { get; set; }
        public int AcademicYearTermID { get; set; }
        public Nullable<decimal> ActualPaymentAmount { get; set; }
        public Nullable<decimal> CalculatedPaymentAmount { get; set; }
        public Nullable<decimal> EffectivePaymentAmount { get; set; }
        public int ProgressCounter { get; set; }
        public bool IsApproved { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> PaidAmount { get; set; }
        public string PaidAmountComment { get; set; }
        public Nullable<decimal> OJTPaymentAmount { get; set; }
    
        public virtual AcademicYearTerm AcademicYearTerm { get; set; }
        public virtual PaymentRequest PaymentRequest { get; set; }
        public virtual PaymentRequestStatus PaymentRequestStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentCoursePayment> StudentCoursePayment { get; set; }
        public virtual College College { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InvoiceRequest> InvoiceRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CollegePaymentAttachement> CollegePaymentAttachement { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMonthlyPayment> StudentMonthlyPayment { get; set; }
    }
}
