//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class ContractCollegeAcademicYear
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContractCollegeAcademicYear()
        {
            this.ContractTermPaymentSetting = new HashSet<ContractTermPaymentSetting>();
        }
    
        public int ID { get; set; }
        public int ContractID { get; set; }
        public int AcademicYearID { get; set; }
        public int CollegeID { get; set; }
        public Nullable<double> Saudization { get; set; }
        public Nullable<int> BasePriceForFoundationStudent { get; set; }
        public Nullable<int> BasePriceForAssociateStudent { get; set; }
        public Nullable<int> BasePriceForDiplomaStudent { get; set; }
        public Nullable<double> FoundationStudentToTeacherRatio { get; set; }
        public Nullable<double> VocationalStudentToTeacherRatio { get; set; }
        public Nullable<double> PracticalStudentToTeacherRatio { get; set; }
        public Nullable<int> PerformancePrice { get; set; }
        public Nullable<int> InstitutionalReview { get; set; }
        public Nullable<int> Assessment { get; set; }
        public Nullable<int> Employability { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AcademicYear AcademicYear { get; set; }
        public virtual College College { get; set; }
        public virtual Contract Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContractTermPaymentSetting> ContractTermPaymentSetting { get; set; }
    }
}
