//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class Course
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Course()
        {
            this.TermCourse = new HashSet<TermCourse>();
            this.EquivalentNOSSCourse = new HashSet<EquivalentNOSSCourse>();
            this.StudentMonthlyPayment = new HashSet<StudentMonthlyPayment>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public string NameAr { get; set; }
        public string Description { get; set; }
        public string DescriptionAr { get; set; }
        public int CreditHours { get; set; }
        public string CourseCode { get; set; }
        public Nullable<decimal> CoursePrice { get; set; }
        public int CourseTypeID { get; set; }
        public int CourseLevelID { get; set; }
        public int SubProgramID { get; set; }
        public int CollegeID { get; set; }
        public int SpecializationID { get; set; }
        public string CourseSequenceNo { get; set; }
        public Nullable<int> UnitID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual College College { get; set; }
        public virtual CourseType CourseType { get; set; }
        public virtual Level Level { get; set; }
        public virtual SubProgram SubProgram { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TermCourse> TermCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EquivalentNOSSCourse> EquivalentNOSSCourse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentMonthlyPayment> StudentMonthlyPayment { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual Unit Unit { get; set; }
    }
}
