//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class DeferralRequest
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DeferralRequest()
        {
            this.DeferralRequestAcademicYearTerm = new HashSet<DeferralRequestAcademicYearTerm>();
            this.DeferralRequestReason = new HashSet<DeferralRequestReason>();
        }
    
        public int ID { get; set; }
        public int EnrollmentID { get; set; }
        public long WorkflowRequestID { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public bool IsAfter3rdWeek { get; set; }
        public string OtherReasons { get; set; }
        public bool IsCurrentTermOnly { get; set; }
    
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeferralRequestAcademicYearTerm> DeferralRequestAcademicYearTerm { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeferralRequestReason> DeferralRequestReason { get; set; }
        public virtual Enrollment Enrollment { get; set; }
    }
}
