//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class DismissRequest
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DismissRequest()
        {
            this.DismissRequestReason = new HashSet<DismissRequestReason>();
        }
    
        public int ID { get; set; }
        public long WorkflowRequestID { get; set; }
        public int EnrollmentID { get; set; }
        public int AcademicYearTermID { get; set; }
        public Nullable<bool> StudentHasObjection { get; set; }
        public string Objection { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
    
        public virtual AcademicYearTerm AcademicYearTerm { get; set; }
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DismissRequestReason> DismissRequestReason { get; set; }
        public virtual Enrollment Enrollment { get; set; }
    }
}
