//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class ExamCalendar
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExamCalendar()
        {
            this.ExamCalendarRequest = new HashSet<ExamCalendarRequest>();
        }
    
        public int ID { get; set; }
        public int AssessmentPeriodComponentID { get; set; }
        public int SpecializationID { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public System.TimeSpan TimeFrom { get; set; }
        public System.TimeSpan TimeTo { get; set; }
        public string Code { get; set; }
        public int ExamCalendarStatusID { get; set; }
        public bool IsRequireApproval { get; set; }
        public bool IsFlexibleDateEditing { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual AssessmentPeriodComponent AssessmentPeriodComponent { get; set; }
        public virtual ExamCalendarStatus ExamCalendarStatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ExamCalendarRequest> ExamCalendarRequest { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
