//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class GetEnrollmentRequestList
    { 
        public int ID { get; set; }
        public int EnrollmentRequestID { get; set; }
        public int CollegeSpecializationID { get; set; }
        public int Priority { get; set; }
        public int StageID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
        public int BatchID { get; set; }
        public int EnrollmentRequestDetailStatusID { get; set; }
        public int EnrollmentRequestStageID { get; set; }
        public int EnrollmentRequestStatusID { get; set; }
        public int CollegeID { get; set; }
        public System.Guid UserID { get; set; }
        public string NationalId { get; set; }
        public string PhoneNumber { get; set; }
        public int StudentProfileID { get; set; }
        public string StudentNameAr { get; set; }
        public string StudentName { get; set; }
        public string CollegeName { get; set; }
        public string CollegeNameAr { get; set; }
        public string SpecializationName { get; set; }
        public string SpecializationNameAr { get; set; }
        public string LoginName { get; set; }
        public int AcademicYearTermId { get; set; }
        public Nullable<System.DateTime> AdmissionStartDate { get; set; }
        public Nullable<System.DateTime> AdmissionEndDate { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public int ProgramID { get; set; }
    }
}
