//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class IncomingExamResultGradingSetting
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IncomingExamResultGradingSetting()
        {
            this.StudentGradeBook = new HashSet<StudentGradeBook>();
            this.StudentGradeBook1 = new HashSet<StudentGradeBook>();
            this.StudentGradeBook2 = new HashSet<StudentGradeBook>();
        }
    
        public int ID { get; set; }
        public int IncomingExamResultID { get; set; }
        public int GradingSchemaSettingID { get; set; }
        public int StatusID { get; set; }
        public string OverAllGPA { get; set; }
        public string OverAllGrade { get; set; }
        public string OverAllPercentage { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Status Status { get; set; }
        public virtual GradingSchemeSetting GradingSchemeSetting { get; set; }
        public virtual IncomingExamResult IncomingExamResult { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGradeBook> StudentGradeBook { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGradeBook> StudentGradeBook1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StudentGradeBook> StudentGradeBook2 { get; set; }
    }
}
