//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class InvoiceRequest
    { 
        public int ID { get; set; }
        public int CollegePaymentID { get; set; }
        public long RequestID { get; set; }
    
        public virtual CollegePayment CollegePayment { get; set; }
        public virtual Request Request { get; set; }
    }
}
