//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class Log
    { 
        public System.Guid Id { get; set; }
        public string AllXml { get; set; }
        public string Application { get; set; }
        public string Browser { get; set; }
        public System.DateTime Date { get; set; }
        public string Exception { get; set; }
        public string ExceptionData { get; set; }
        public string ExceptionType { get; set; }
        public string Host { get; set; }
        public string Level { get; set; }
        public string Logger { get; set; }
        public string Message { get; set; }
        public Nullable<int> StatusCode { get; set; }
        public string Thread { get; set; }
        public string Url { get; set; }
        public string User { get; set; }
    }
}
