//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class ReinstateRequest
    { 
        public int ID { get; set; }
        public long WorkflowRequestID { get; set; }
        public int EnrollmentID { get; set; }
        public Nullable<int> NewEnrollmentID { get; set; }
        public int CurrentAcademicYearTermID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AcademicYearTerm AcademicYearTerm { get; set; }
        public virtual Request Request { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual Enrollment Enrollment1 { get; set; }
    }
}
