//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class RPLApplicant
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RPLApplicant()
        {
            this.ApplicantExperince = new HashSet<ApplicantExperince>();
            this.RPLApplicantAttachment = new HashSet<RPLApplicantAttachment>();
            this.RPLQualification = new HashSet<RPLQualification>();
            this.RPLRequest = new HashSet<RPLRequest>();
        }
    
        public int ID { get; set; }
        public System.Guid UserID { get; set; }
        public string FirstName { get; set; }
        public bool FirstNameIsFromYakeen { get; set; }
        public string FirstNameAr { get; set; }
        public bool FirstNameArIsFromYakeen { get; set; }
        public string SecondName { get; set; }
        public bool SecondNameIsFromYakeen { get; set; }
        public string SecondNameAr { get; set; }
        public bool SecondNameArIsFromYakeen { get; set; }
        public string ThirdName { get; set; }
        public bool ThirdNameIsFromYakeen { get; set; }
        public string ThirdNameAr { get; set; }
        public bool ThirdNameArIsFromYakeen { get; set; }
        public string FourthName { get; set; }
        public bool FourthNameIsFromYakeen { get; set; }
        public string FourthNameAr { get; set; }
        public bool FourthNameArIsFromYakeen { get; set; }
        public System.DateTime Birthdate { get; set; }
        public bool BirthDateIsFromYakeen { get; set; }
        public bool Gender { get; set; }
        public bool GenderIsFromYakeen { get; set; }
        public Nullable<int> CityID { get; set; }
        public Nullable<short> ExperienceYears { get; set; }
        public Nullable<short> ExperienceMonths { get; set; }
        public Nullable<short> OSHExperienceYears { get; set; }
        public Nullable<short> OSHExperienceMonths { get; set; }
        public Nullable<bool> IsArabicSpeaking { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual City City { get; set; }
        public virtual AspNetUsers AspNetUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApplicantExperince> ApplicantExperince { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPLApplicantAttachment> RPLApplicantAttachment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPLQualification> RPLQualification { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPLRequest> RPLRequest { get; set; }
    }
}
