//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class RPLExamResult
    { 
        public System.Guid USERID { get; set; }
        public string FinalOverAllGrade { get; set; }
        public decimal FinalOverAllPercentage { get; set; }
        public int StageID { get; set; }
        public Nullable<System.DateTime> Createdon { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<int> RPLCertificateTypeID { get; set; }
        public string SerialNumber { get; set; }
        public int ID { get; set; }
        public Nullable<int> ExambookingID { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual RPLCertificateType RPLCertificateType { get; set; }
        public virtual RPLExamBooking RPLExamBooking { get; set; }
    }
}
