//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class RPLExamBookingNotification
    { 
        public int Id { get; set; }
        public int ExamBookingId { get; set; }
        public System.Guid NotificationQueueId { get; set; }
        public int NotificationTypeId { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual RPLExamBooking RPLExamBooking { get; set; }
        public virtual RPLExamBookingNotificationType RPLExamBookingNotificationType { get; set; }
        public virtual NotificationQueue NotificationQueue { get; set; }
    }
}
