//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class RPLRequest
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RPLRequest()
        {
            this.RPLCertificate = new HashSet<RPLCertificate>();
            this.RPLExamBookingPayment = new HashSet<RPLExamBookingPayment>();
            this.RPLRequestPayment = new HashSet<RPLRequestPayment>();
        }
    
        public int ID { get; set; }
        public int RPLApplicantID { get; set; }
        public Nullable<long> RequestID { get; set; }
        public string InstituteName { get; set; }
        public Nullable<decimal> InstituteLatitude { get; set; }
        public Nullable<decimal> InstituteLongitude { get; set; }
        public string CertificateName { get; set; }
        public string InstituteAddress { get; set; }
        public int QualificationLevelID { get; set; }
        public int CityID { get; set; }
        public System.DateTime StudyStartDate { get; set; }
        public System.DateTime GraduationDate { get; set; }
        public int StageID { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual Stage Stage { get; set; }
        public virtual QualificationLevel QualificationLevel { get; set; }
        public virtual RPLApplicant RPLApplicant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPLCertificate> RPLCertificate { get; set; }
        public virtual RPLCity RPLCity { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPLExamBookingPayment> RPLExamBookingPayment { get; set; }
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RPLRequestPayment> RPLRequestPayment { get; set; }
    }
}
