//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class SectionEnrollmentValidation
    { 
        public int ID { get; set; }
        public string CourseCode { get; set; }
        public string NationalID { get; set; }
        public string SectionCode { get; set; }
        public string EnrollmentStatus { get; set; }
        public int UploadRejectionReasonID { get; set; }
        public int UploadRequestID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual UploadRejectionReason UploadRejectionReason { get; set; }
        public virtual UploadRequest UploadRequest { get; set; }
    }
}
