//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class SpecializationStatistic
    { 
        public int ID { get; set; }
        public int SpecializationID { get; set; }
        public int EnrollmentStatisticID { get; set; }
        public int NumberOfNew { get; set; }
        public int NumberOfContinuing { get; set; }
        public int NumberOfRepeats { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual EnrollmentStatistic EnrollmentStatistic { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
