//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class SpecializationComponentAssessment
    { 
        public int ID { get; set; }
        public int SpecializationID { get; set; }
        public int AssessmentComponentID { get; set; }
        public int GradingRuleID { get; set; }
        public int Weight { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual AssessmentComponent AssessmentComponent { get; set; }
        public virtual GradingRule GradingRule { get; set; }
        public virtual Specialization Specialization { get; set; }
    }
}
