//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class StudentFailureIntegrationLog
    { 
        public long Id { get; set; }
        public int ProgramID { get; set; }
        public int ServiceTypeID { get; set; }
        public string NationalId { get; set; }
        public string Message { get; set; }
        public string StatusCode { get; set; }
        public string Code { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Program Program { get; set; }
        public virtual ServiceType ServiceType { get; set; }
    }
}
