//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class StudentMonthlyPayment
    { 
        public int ID { get; set; }
        public int CollegePaymentID { get; set; }
        public int EnrollmentID { get; set; }
        public int CourseID { get; set; }
        public double CalculatedAmount { get; set; }
        public int PayableFactor { get; set; }
        public int RepetitionFactor { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public decimal OfferedHours { get; set; }
        public decimal Attended { get; set; }
        public decimal Excused { get; set; }
        public decimal Extra { get; set; }
        public decimal OJT { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual CollegePayment CollegePayment { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual Course Course { get; set; }
    }
}
