//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class TransferRequest
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TransferRequest()
        {
            this.TransferRequestReason = new HashSet<TransferRequestReason>();
        }
    
        public int ID { get; set; }
        public long WorkflowRequestID { get; set; }
        public int EnrollmentID { get; set; }
        public int TransferAcademicYearTermID { get; set; }
        public int NewCollegeSpecializationID { get; set; }
        public string OtherReasons { get; set; }
        public Nullable<int> FundingLevelID { get; set; }
        public Nullable<int> FundingSpecializationID { get; set; }
        public Nullable<int> SSSExamID { get; set; }
        public Nullable<decimal> SSSExamResult { get; set; }
        public Nullable<int> NoOfFullFundedTerms { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual AcademicYearTerm AcademicYearTerm { get; set; }
        public virtual SSSExam SSSExam { get; set; }
        public virtual Request Request { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TransferRequestReason> TransferRequestReason { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual CollegeSpecialization CollegeSpecialization { get; set; }
        public virtual Specialization Specialization { get; set; }
        public virtual Specialization Specialization1 { get; set; }
    }
}
