//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class UploadRequestHistory
    { 
        public int ID { get; set; }
        public int UploadRequestTypeID { get; set; }
        public Nullable<int> NoOfRecords { get; set; }
        public Nullable<int> NoOfInValidRecords { get; set; }
        public int RecordProgress { get; set; }
        public int UploadRequestStatusID { get; set; }
        public string UploadedFileURL { get; set; }
        public int ProgressTypeID { get; set; }
        public bool IsProgressCompleted { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public System.DateTime StartTime { get; set; }
        public System.DateTime EndTime { get; set; }
    }
}
