//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class Vacancy
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vacancy()
        {
            this.CandidateVacancyRequest = new HashSet<CandidateVacancyRequest>();
            this.Interview = new HashSet<Interview>();
            this.VacancySkill = new HashSet<VacancySkill>();
        }
    
        public int ID { get; set; }
        public int EmployerID { get; set; }
        public string Name { get; set; }
        public int CityID { get; set; }
        public System.DateTime OpeningDate { get; set; }
        public System.DateTime ClosingDate { get; set; }
        public int StageID { get; set; }
        public string Purpose { get; set; }
        public string Requirement { get; set; }
        public string Code { get; set; }
        public string Industry { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
    
        public virtual City City { get; set; }
        public virtual Stage Stage { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CandidateVacancyRequest> CandidateVacancyRequest { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Interview> Interview { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VacancySkill> VacancySkill { get; set; }
        public virtual Employer Employer { get; set; }
    }
}
