//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class VocationalExamResult
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VocationalExamResult()
        {
            this.VocationalExamResultDetail = new HashSet<VocationalExamResultDetail>();
        }
    
        public int ID { get; set; }
        public int EnrollmentID { get; set; }
        public int CollegeSpecializationID { get; set; }
        public int AcademicYearTermID { get; set; }
        public int LevelID { get; set; }
        public int ExamStatusID { get; set; }
        public int OverAllVocationalExamScoreID { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
        public Nullable<decimal> GPA { get; set; }
    
        public virtual AcademicYearTerm AcademicYearTerm { get; set; }
        public virtual Level Level { get; set; }
        public virtual ExamStatus ExamStatus { get; set; }
        public virtual VocationalExamScore VocationalExamScore { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VocationalExamResultDetail> VocationalExamResultDetail { get; set; }
        public virtual Enrollment Enrollment { get; set; }
        public virtual CollegeSpecialization CollegeSpecialization { get; set; }
    }
}
