//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Model
{
     
    using System;
    using System.Collections.Generic;
       
    public partial class ZATCAInvoiceIntegration
    { 
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ZATCAInvoiceIntegration()
        {
            this.ZATCAInvoiceIntegrationLog = new HashSet<ZATCAInvoiceIntegrationLog>();
        }
    
        public int Id { get; set; }
        public Nullable<int> InvoiceId { get; set; }
        public Nullable<int> CreditNoteId { get; set; }
        public Nullable<System.Guid> SignedInvoiceAttachmentID { get; set; }
        public string InvoiceHash { get; set; }
        public System.Guid UUID { get; set; }
        public string ReportingStatus { get; set; }
        public string ValidationStatus { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime UpdatedOn { get; set; }
        public string UpdatedBy { get; set; }
    
        public virtual Attachments Attachments { get; set; }
        public virtual RPLExamBookingInvoiceCreditNote RPLExamBookingInvoiceCreditNote { get; set; }
        public virtual RPLExamBookingPaymentInvoice RPLExamBookingPaymentInvoice { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZATCAInvoiceIntegrationLog> ZATCAInvoiceIntegrationLog { get; set; }
    }
}
