//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ComplaintRequestResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ComplaintRequestResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.Workflow.ComplaintRequestResource", typeof(ComplaintRequestResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Application.
        /// </summary>
        public static string ComplaintApplication {
            get {
                return ResourceManager.GetString("ComplaintApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Date.
        /// </summary>
        public static string ComplaintDate {
            get {
                return ResourceManager.GetString("ComplaintDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Description.
        /// </summary>
        public static string ComplaintDescription {
            get {
                return ResourceManager.GetString("ComplaintDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length {0} should not exceed 1000 digits.
        /// </summary>
        public static string ComplaintDescriptionMaxLength {
            get {
                return ResourceManager.GetString("ComplaintDescriptionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Number.
        /// </summary>
        public static string ComplaintNumber {
            get {
                return ResourceManager.GetString("ComplaintNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Category.
        /// </summary>
        public static string ComplaintParentType {
            get {
                return ResourceManager.GetString("ComplaintParentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Complaints.
        /// </summary>
        public static string Complaints {
            get {
                return ResourceManager.GetString("Complaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Details.
        /// </summary>
        public static string ComplaintsDetails {
            get {
                return ResourceManager.GetString("ComplaintsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Status.
        /// </summary>
        public static string ComplaintStage {
            get {
                return ResourceManager.GetString("ComplaintStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Subject.
        /// </summary>
        public static string ComplaintSubject {
            get {
                return ResourceManager.GetString("ComplaintSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum length {0} should not exceed 250 digits.
        /// </summary>
        public static string ComplaintSubjectMaxLength {
            get {
                return ResourceManager.GetString("ComplaintSubjectMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint tracking.
        /// </summary>
        public static string ComplaintTracking {
            get {
                return ResourceManager.GetString("ComplaintTracking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint Type.
        /// </summary>
        public static string ComplaintType {
            get {
                return ResourceManager.GetString("ComplaintType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The complaints service is only available for enrolled trainees.
        /// </summary>
        public static string EnrollebOnlyCanSubmitComplaints {
            get {
                return ResourceManager.GetString("EnrollebOnlyCanSubmitComplaints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exam result manager decision.
        /// </summary>
        public static string ExamResultManagerDecision {
            get {
                return ResourceManager.GetString("ExamResultManagerDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to exam result supervisor decision.
        /// </summary>
        public static string ExamResultSupervisorDecision {
            get {
                return ResourceManager.GetString("ExamResultSupervisorDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grading manager decision.
        /// </summary>
        public static string GradingManagerDecision {
            get {
                return ResourceManager.GetString("GradingManagerDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grading supervisor decision.
        /// </summary>
        public static string GradingSupervisorDecision {
            get {
                return ResourceManager.GetString("GradingSupervisorDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training program manager&apos;s decision.
        /// </summary>
        public static string ProgramManagerDecision {
            get {
                return ResourceManager.GetString("ProgramManagerDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training program supervisor&apos;s decision.
        /// </summary>
        public static string ProgramSupervisorDecision {
            get {
                return ResourceManager.GetString("ProgramSupervisorDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainee objection.
        /// </summary>
        public static string TraineeObjection {
            get {
                return ResourceManager.GetString("TraineeObjection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainees service manager decision.
        /// </summary>
        public static string TraineeServiceManagerDecision {
            get {
                return ResourceManager.GetString("TraineeServiceManagerDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trainees service supervisor decision.
        /// </summary>
        public static string TraineeServiceSupervisorDecision {
            get {
                return ResourceManager.GetString("TraineeServiceSupervisorDecision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complaint update.
        /// </summary>
        public static string TraineeUpdate {
            get {
                return ResourceManager.GetString("TraineeUpdate", resourceCulture);
            }
        }
    }
}
