//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Workflow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WithdrawRequestResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WithdrawRequestResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.Workflow.WithdrawRequestResources", typeof(WithdrawRequestResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivityName.
        /// </summary>
        public static string ActivityName {
            get {
                return ResourceManager.GetString("ActivityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AllocatedUser.
        /// </summary>
        public static string AllocatedUser {
            get {
                return ResourceManager.GetString("AllocatedUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot submit the withdrawal request due to the expiry of the submission period of withdrawal requests.
        /// </summary>
        public static string ApplicationPeriodEnded {
            get {
                return ResourceManager.GetString("ApplicationPeriodEnded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Attachment.
        /// </summary>
        public static string AttachedFileName {
            get {
                return ResourceManager.GetString("AttachedFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake students are not allowed to submit withdrawal request till DayTen.
        /// </summary>
        public static string CanNotSubmitRequestForIntakeStudentsTillDayTen {
            get {
                return ResourceManager.GetString("CanNotSubmitRequestForIntakeStudentsTillDayTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Counselor Comment.
        /// </summary>
        public static string CounselorComment {
            get {
                return ResourceManager.GetString("CounselorComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details Module Title.
        /// </summary>
        public static string DetailsModuleTitle {
            get {
                return ResourceManager.GetString("DetailsModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string DetailsTitle {
            get {
                return ResourceManager.GetString("DetailsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error has occurred.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string InboxModuleTitle {
            get {
                return ResourceManager.GetString("InboxModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Tasks.
        /// </summary>
        public static string InboxTasks {
            get {
                return ResourceManager.GetString("InboxTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No data to display.
        /// </summary>
        public static string NoDataToDisplay {
            get {
                return ResourceManager.GetString("NoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OriginatorName.
        /// </summary>
        public static string OriginatorName {
            get {
                return ResourceManager.GetString("OriginatorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process Name.
        /// </summary>
        public static string ProcessName {
            get {
                return ResourceManager.GetString("ProcessName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestDate.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Name.
        /// </summary>
        public static string RequestName {
            get {
                return ResourceManager.GetString("RequestName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestNameAr.
        /// </summary>
        public static string RequestNameAr {
            get {
                return ResourceManager.GetString("RequestNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestNameEn.
        /// </summary>
        public static string RequestNameEn {
            get {
                return ResourceManager.GetString("RequestNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Number.
        /// </summary>
        public static string RequestNumber {
            get {
                return ResourceManager.GetString("RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Your withdraw request has not updated.
        /// </summary>
        public static string RequestUpdatedFailed {
            get {
                return ResourceManager.GetString("RequestUpdatedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your withdraw request has been sent successfully.
        /// </summary>
        public static string RequestUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("RequestUpdatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SerialNumber.
        /// </summary>
        public static string SerialNumber {
            get {
                return ResourceManager.GetString("SerialNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage Name.
        /// </summary>
        public static string StageName {
            get {
                return ResourceManager.GetString("StageName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StageNameAr.
        /// </summary>
        public static string StageNameAr {
            get {
                return ResourceManager.GetString("StageNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StageNameEn.
        /// </summary>
        public static string StageNameEn {
            get {
                return ResourceManager.GetString("StageNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Withdraw Request Module Title.
        /// </summary>
        public static string StartWithdrawRequestModuleTitle {
            get {
                return ResourceManager.GetString("StartWithdrawRequestModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Withdraw Request.
        /// </summary>
        public static string StartWithdrawRequestTitle {
            get {
                return ResourceManager.GetString("StartWithdrawRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Counselor Review Module Title.
        /// </summary>
        public static string StudentCounselorReviewModuleTitle {
            get {
                return ResourceManager.GetString("StudentCounselorReviewModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Counselor Review Title.
        /// </summary>
        public static string StudentCounselorReviewTitle {
            get {
                return ResourceManager.GetString("StudentCounselorReviewTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student FullName.
        /// </summary>
        public static string StudentFullName {
            get {
                return ResourceManager.GetString("StudentFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student National ID.
        /// </summary>
        public static string StudentNationalID {
            get {
                return ResourceManager.GetString("StudentNationalID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Service Close Request Module Title.
        /// </summary>
        public static string StudentServiceCloseRequestModuleTitle {
            get {
                return ResourceManager.GetString("StudentServiceCloseRequestModuleTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Service Close Request Title.
        /// </summary>
        public static string StudentServiceCloseRequestTitle {
            get {
                return ResourceManager.GetString("StudentServiceCloseRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Services Comment.
        /// </summary>
        public static string StudentServicesComment {
            get {
                return ResourceManager.GetString("StudentServicesComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Request is submitted successfully.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Requests.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserFullName.
        /// </summary>
        public static string UserFullName {
            get {
                return ResourceManager.GetString("UserFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Request Reasons.
        /// </summary>
        public static string WithdrawRequestReason {
            get {
                return ResourceManager.GetString("WithdrawRequestReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Attachments.
        /// </summary>
        public static string WithdrawRequestReasonAttached {
            get {
                return ResourceManager.GetString("WithdrawRequestReasonAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to download.
        /// </summary>
        public static string WithdrawRequestReasonAttachmentUrl {
            get {
                return ResourceManager.GetString("WithdrawRequestReasonAttachmentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reason Comments.
        /// </summary>
        public static string WithdrawRequestReasonComments {
            get {
                return ResourceManager.GetString("WithdrawRequestReasonComments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkflowID.
        /// </summary>
        public static string WorkflowIDAsProcessName {
            get {
                return ResourceManager.GetString("WorkflowIDAsProcessName", resourceCulture);
            }
        }
    }
}
