//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RM.Workflow {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WorkflowSharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WorkflowSharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.Workflow.WorkflowSharedResources", typeof(WorkflowSharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you cannot submit the transfer request due to the expiry of the submission period of transfer requests.
        /// </summary>
        public static string ApplicationPeriodEnded_Transfer {
            get {
                return ResourceManager.GetString("ApplicationPeriodEnded_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , It is not allowed to submit this request for intake students ..
        /// </summary>
        public static string CanNotSubmitRequestForIntakeStudents {
            get {
                return ResourceManager.GetString("CanNotSubmitRequestForIntakeStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can not submit this request  because of  the registration period has expired.
        /// </summary>
        public static string CanNotSubmitRequestPeriodExpired {
            get {
                return ResourceManager.GetString("CanNotSubmitRequestPeriodExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry please check if this college has any academic year terms in current academic year.
        /// </summary>
        public static string CheckIfCollegeHasAcademicYearTerms {
            get {
                return ResourceManager.GetString("CheckIfCollegeHasAcademicYearTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferral.
        /// </summary>
        public static string Deferral {
            get {
                return ResourceManager.GetString("Deferral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, all current academic year semesters has been deferred.
        /// </summary>
        public static string DeferralAllAcademicYearTermsAreDeferred {
            get {
                return ResourceManager.GetString("DeferralAllAcademicYearTermsAreDeferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Workflows/DeferralRequest/Details?requestId=.
        /// </summary>
        public static string DeferralRequestDetailsUrl {
            get {
                return ResourceManager.GetString("DeferralRequestDetailsUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss.
        /// </summary>
        public static string Dismiss {
            get {
                return ResourceManager.GetString("Dismiss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flow Digram.
        /// </summary>
        public static string FlowDigram {
            get {
                return ResourceManager.GetString("FlowDigram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can not submit a new request because this student has an existing request(s) : {0} ..
        /// </summary>
        public static string HasInprogressRequests {
            get {
                return ResourceManager.GetString("HasInprogressRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, failed to send request because of the students whose identity numbers {0} are already in progress request ..
        /// </summary>
        public static string HaveInProgressChangeStatusRequest {
            get {
                return ResourceManager.GetString("HaveInProgressChangeStatusRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, you can&apos;t apply new request , you already have an inprogress request.
        /// </summary>
        public static string HaveInProgressRequest {
            get {
                return ResourceManager.GetString("HaveInProgressRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request was successfully cancelled.
        /// </summary>
        public static string K2CancelledSuccessfully {
            get {
                return ResourceManager.GetString("K2CancelledSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this task has already been decided.
        /// </summary>
        public static string K2WorklistItemDone {
            get {
                return ResourceManager.GetString("K2WorklistItemDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, failed to make a decision. Please try again.
        /// </summary>
        public static string K2WorklistItemFailure {
            get {
                return ResourceManager.GetString("K2WorklistItemFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are not allowed to open the worklist item .
        /// </summary>
        public static string K2WorklistItemNotAllow {
            get {
                return ResourceManager.GetString("K2WorklistItemNotAllow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The decision was successfully taken .
        /// </summary>
        public static string K2WorklistItemSuccess {
            get {
                return ResourceManager.GetString("K2WorklistItemSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests By Type.
        /// </summary>
        public static string RequestsByType {
            get {
                return ResourceManager.GetString("RequestsByType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, failed to send request . Please try again.
        /// </summary>
        public static string RequestSentFailed {
            get {
                return ResourceManager.GetString("RequestSentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has been sent successfully.
        /// </summary>
        public static string RequestSentSuccess {
            get {
                return ResourceManager.GetString("RequestSentSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , please confirm if you already select student enrollment to do this procedure.
        /// </summary>
        public static string SelectEnrollment {
            get {
                return ResourceManager.GetString("SelectEnrollment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , You cannot submit this request because of closing registration period of {0} ..
        /// </summary>
        public static string SubmitPeriodClosed {
            get {
                return ResourceManager.GetString("SubmitPeriodClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today tasks.
        /// </summary>
        public static string TodayTasks {
            get {
                return ResourceManager.GetString("TodayTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no task in today tasks list ..
        /// </summary>
        public static string TodayTasksNoDataToDisplay {
            get {
                return ResourceManager.GetString("TodayTasksNoDataToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Transfer {
            get {
                return ResourceManager.GetString("Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw.
        /// </summary>
        public static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
    }
}
