//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StipendResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StipendResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.Stipend.StipendResources", typeof(StipendResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year.
        /// </summary>
        public static string AcademicYearID {
            get {
                return ResourceManager.GetString("AcademicYearID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acadimic Term.
        /// </summary>
        public static string AcadimicTerm {
            get {
                return ResourceManager.GetString("AcadimicTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acadimic Year.
        /// </summary>
        public static string AcadimicYear {
            get {
                return ResourceManager.GetString("AcadimicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string AcceptedInPeriod {
            get {
                return ResourceManager.GetString("AcceptedInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request accepted successfully.
        /// </summary>
        public static string AcceptedSuccess {
            get {
                return ResourceManager.GetString("AcceptedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to accept this request?.
        /// </summary>
        public static string AcceptRequestConfirm {
            get {
                return ResourceManager.GetString("AcceptRequestConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Actions_Back {
            get {
                return ResourceManager.GetString("Actions_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View validation errors.
        /// </summary>
        public static string Actions_btnViewInvalidRecords {
            get {
                return ResourceManager.GetString("Actions_btnViewInvalidRecords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Actions_Cancel {
            get {
                return ResourceManager.GetString("Actions_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Actions_Download {
            get {
                return ResourceManager.GetString("Actions_Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download Feedback.
        /// </summary>
        public static string Actions_DownloadFeedback {
            get {
                return ResourceManager.GetString("Actions_DownloadFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Actions_Edit {
            get {
                return ResourceManager.GetString("Actions_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate.
        /// </summary>
        public static string Actions_Generate {
            get {
                return ResourceManager.GetString("Actions_Generate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions_Header {
            get {
                return ResourceManager.GetString("Actions_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        public static string Actions_History {
            get {
                return ResourceManager.GetString("Actions_History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Actions_Search {
            get {
                return ResourceManager.GetString("Actions_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Actions_Upload {
            get {
                return ResourceManager.GetString("Actions_Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Feedback.
        /// </summary>
        public static string Actions_UploadFeedback {
            get {
                return ResourceManager.GetString("Actions_UploadFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string Actions_View {
            get {
                return ResourceManager.GetString("Actions_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approve Request.
        /// </summary>
        public static string ApproveRequest {
            get {
                return ResourceManager.GetString("ApproveRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVTC NO.
        /// </summary>
        public static string AspNetUsers_TVTCNo {
            get {
                return ResourceManager.GetString("AspNetUsers_TVTCNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string Cards_BankIBAN {
            get {
                return ResourceManager.GetString("Cards_BankIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        public static string Cards_CardNo {
            get {
                return ResourceManager.GetString("Cards_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Cards_CardStudentType {
            get {
                return ResourceManager.GetString("Cards_CardStudentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejection Reason.
        /// </summary>
        public static string Cards_FeedbackDenialReason {
            get {
                return ResourceManager.GetString("Cards_FeedbackDenialReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Cards_FeedbackStatus {
            get {
                return ResourceManager.GetString("Cards_FeedbackStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Generation Failed.
        /// </summary>
        public static string Cards_FileGenerationError {
            get {
                return ResourceManager.GetString("Cards_FileGenerationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Generation In Progress ....
        /// </summary>
        public static string Cards_FileGenerationInProgress {
            get {
                return ResourceManager.GetString("Cards_FileGenerationInProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Generated Successfully.
        /// </summary>
        public static string Cards_FileGenerationSuccess {
            get {
                return ResourceManager.GetString("Cards_FileGenerationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Cards_Header_Requests_Search {
            get {
                return ResourceManager.GetString("Cards_Header_Requests_Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card No.
        /// </summary>
        public static string Cards_Title_CardNo {
            get {
                return ResourceManager.GetString("Cards_Title_CardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Request History.
        /// </summary>
        public static string Cards_Title_CardRequestHistory {
            get {
                return ResourceManager.GetString("Cards_Title_CardRequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Cards_Title_Cards {
            get {
                return ResourceManager.GetString("Cards_Title_Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards Management.
        /// </summary>
        public static string Cards_Title_CardsManagement {
            get {
                return ResourceManager.GetString("Cards_Title_CardsManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Generation.
        /// </summary>
        public static string Cards_Title_FileGeneration {
            get {
                return ResourceManager.GetString("Cards_Title_FileGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Management.
        /// </summary>
        public static string Cards_Title_FileManagment {
            get {
                return ResourceManager.GetString("Cards_Title_FileManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name.
        /// </summary>
        public static string Cards_Title_FullName {
            get {
                return ResourceManager.GetString("Cards_Title_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Cards_Title_Home {
            get {
                return ResourceManager.GetString("Cards_Title_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IBAN.
        /// </summary>
        public static string Cards_Title_IBAN {
            get {
                return ResourceManager.GetString("Cards_Title_IBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        public static string Cards_Title_Module {
            get {
                return ResourceManager.GetString("Cards_Title_Module", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to National ID.
        /// </summary>
        public static string Cards_Title_NationalId {
            get {
                return ResourceManager.GetString("Cards_Title_NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Request.
        /// </summary>
        public static string Cards_Title_NewRequest {
            get {
                return ResourceManager.GetString("Cards_Title_NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reissuance  Request.
        /// </summary>
        public static string Cards_Title_ReissuanceRequest {
            get {
                return ResourceManager.GetString("Cards_Title_ReissuanceRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string Cards_Title_RequestDetails {
            get {
                return ResourceManager.GetString("Cards_Title_RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request File.
        /// </summary>
        public static string Cards_Title_RequestFile {
            get {
                return ResourceManager.GetString("Cards_Title_RequestFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback File.
        /// </summary>
        public static string Cards_Title_RequestFileFeedback {
            get {
                return ResourceManager.GetString("Cards_Title_RequestFileFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Management.
        /// </summary>
        public static string Cards_Title_RequestManagement {
            get {
                return ResourceManager.GetString("Cards_Title_RequestManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Management.
        /// </summary>
        public static string Cards_Title_RequestManagment {
            get {
                return ResourceManager.GetString("Cards_Title_RequestManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Requests.
        /// </summary>
        public static string Cards_Title_Requests {
            get {
                return ResourceManager.GetString("Cards_Title_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Cards_Title_Status {
            get {
                return ResourceManager.GetString("Cards_Title_Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Cards_Title_StudentDetails {
            get {
                return ResourceManager.GetString("Cards_Title_StudentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Cards_Title_Students {
            get {
                return ResourceManager.GetString("Cards_Title_Students", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Cards_Title_Submit {
            get {
                return ResourceManager.GetString("Cards_Title_Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Card Request.
        /// </summary>
        public static string Cards_Title_SubmitCardRequest {
            get {
                return ResourceManager.GetString("Cards_Title_SubmitCardRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer.
        /// </summary>
        public static string Cards_Title_Transfer {
            get {
                return ResourceManager.GetString("Cards_Title_Transfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVTC.
        /// </summary>
        public static string Cards_Title_TVTC {
            get {
                return ResourceManager.GetString("Cards_Title_TVTC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Feedback.
        /// </summary>
        public static string Cards_Title_UploadFeedback {
            get {
                return ResourceManager.GetString("Cards_Title_UploadFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validation Errors.
        /// </summary>
        public static string Cards_Title_ValidationErrors {
            get {
                return ResourceManager.GetString("Cards_Title_ValidationErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Students.
        /// </summary>
        public static string CardsRequest_AllStudents {
            get {
                return ResourceManager.GetString("CardsRequest_AllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Status.
        /// </summary>
        public static string CardsRequest_FeedbackUploadStatus {
            get {
                return ResourceManager.GetString("CardsRequest_FeedbackUploadStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Generation.
        /// </summary>
        public static string CardsRequest_FileAutoGenerationStatus {
            get {
                return ResourceManager.GetString("CardsRequest_FileAutoGenerationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string CardsRequest_FileUrl {
            get {
                return ResourceManager.GetString("CardsRequest_FileUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Accepted.
        /// </summary>
        public static string CardsRequest_NoOfAccepted {
            get {
                return ResourceManager.GetString("CardsRequest_NoOfAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Rejected.
        /// </summary>
        public static string CardsRequest_NoOfRejected {
            get {
                return ResourceManager.GetString("CardsRequest_NoOfRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Students.
        /// </summary>
        public static string CardsRequest_NoOfStudents {
            get {
                return ResourceManager.GetString("CardsRequest_NoOfStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intake.
        /// </summary>
        public static string CardsRequestManagement_NoOfIntakeStudents {
            get {
                return ResourceManager.GetString("CardsRequestManagement_NoOfIntakeStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string CardsRequestManagement_NoOfRejected {
            get {
                return ResourceManager.GetString("CardsRequestManagement_NoOfRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string CardsRequestManagement_NoOfStudents {
            get {
                return ResourceManager.GetString("CardsRequestManagement_NoOfStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has Card.
        /// </summary>
        public static string CardsRequestManagement_NoOfStudentsHasCards {
            get {
                return ResourceManager.GetString("CardsRequestManagement_NoOfStudentsHasCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Has No Card.
        /// </summary>
        public static string CardsRequestManagement_NoOfStudentsHasNoCards {
            get {
                return ResourceManager.GetString("CardsRequestManagement_NoOfStudentsHasNoCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferred.
        /// </summary>
        public static string CardsRequestManagement_NoOfTransfer {
            get {
                return ResourceManager.GetString("CardsRequestManagement_NoOfTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepted.
        /// </summary>
        public static string Common__CardsFeedBackStatus_Accepted {
            get {
                return ResourceManager.GetString("Common__CardsFeedBackStatus_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string Common__CardsFeedBackStatus_Rejected {
            get {
                return ResourceManager.GetString("Common__CardsFeedBackStatus_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string Common_AdvancedSearch {
            get {
                return ResourceManager.GetString("Common_AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string Common_College {
            get {
                return ResourceManager.GetString("Common_College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback Status.
        /// </summary>
        public static string Common_FeedbackStatus {
            get {
                return ResourceManager.GetString("Common_FeedbackStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Generation.
        /// </summary>
        public static string Common_FileGenerationStatus {
            get {
                return ResourceManager.GetString("Common_FileGenerationStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Common_FileUploadAttachment {
            get {
                return ResourceManager.GetString("Common_FileUploadAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please upload valid format (.csv).
        /// </summary>
        public static string Common_FileUploadValidExtensions {
            get {
                return ResourceManager.GetString("Common_FileUploadValidExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request No.
        /// </summary>
        public static string Common_RequestNo {
            get {
                return ResourceManager.GetString("Common_RequestNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string Common_RequestStatus {
            get {
                return ResourceManager.GetString("Common_RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Type.
        /// </summary>
        public static string Common_RequestType {
            get {
                return ResourceManager.GetString("Common_RequestType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stipend No.
        /// </summary>
        public static string Common_StipendNo {
            get {
                return ResourceManager.GetString("Common_StipendNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stipend.
        /// </summary>
        public static string Common_Title_Stipend {
            get {
                return ResourceManager.GetString("Common_Title_Stipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Period.
        /// </summary>
        public static string CreatePeriod {
            get {
                return ResourceManager.GetString("CreatePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Days Of Month.
        /// </summary>
        public static string DaysOfMonth {
            get {
                return ResourceManager.GetString("DaysOfMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string DDL_DefaultSelect {
            get {
                return ResourceManager.GetString("DDL_DefaultSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled Request.
        /// </summary>
        public static string DisabledRequest {
            get {
                return ResourceManager.GetString("DisabledRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Period.
        /// </summary>
        public static string EditPeriod {
            get {
                return ResourceManager.GetString("EditPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TVTC No.
        /// </summary>
        public static string Enrollment_TVTCStudentNo {
            get {
                return ResourceManager.GetString("Enrollment_TVTCStudentNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot Delete Item.
        /// </summary>
        public static string ErrorMessageCannotDelete {
            get {
                return ResourceManager.GetString("ErrorMessageCannotDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete item because it has related data.
        /// </summary>
        public static string ErrorMessageCannotDeleteRelated {
            get {
                return ResourceManager.GetString("ErrorMessageCannotDeleteRelated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Occured.
        /// </summary>
        public static string ErrorOccured {
            get {
                return ResourceManager.GetString("ErrorOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Period Already Exist.
        /// </summary>
        public static string ErrorPeriodAlreadyExist {
            get {
                return ResourceManager.GetString("ErrorPeriodAlreadyExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment file is empty , please select another file.
        /// </summary>
        public static string Errors_AttachmentIsEmpty {
            get {
                return ResourceManager.GetString("Errors_AttachmentIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error happened while saving , please try again later.
        /// </summary>
        public static string Errors_Save {
            get {
                return ResourceManager.GetString("Errors_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From Day.
        /// </summary>
        public static string FromDay {
            get {
                return ResourceManager.GetString("FromDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Paid.
        /// </summary>
        public static string FullPaid {
            get {
                return ResourceManager.GetString("FullPaid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string HijriMonth {
            get {
                return ResourceManager.GetString("HijriMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        public static string HijriYear {
            get {
                return ResourceManager.GetString("HijriYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is pending requests for this college.
        /// </summary>
        public static string Message_ThereIsPendingRequestInForCollege {
            get {
                return ResourceManager.GetString("Message_ThereIsPendingRequestInForCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly Stipend.
        /// </summary>
        public static string MonthlyStipend {
            get {
                return ResourceManager.GetString("MonthlyStipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New request created successfully.
        /// </summary>
        public static string NewRequestCreated {
            get {
                return ResourceManager.GetString("NewRequestCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Card No.
        /// </summary>
        public static string NotValidCardNo {
            get {
                return ResourceManager.GetString("NotValidCardNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IBAN.
        /// </summary>
        public static string NotValidIBAN {
            get {
                return ResourceManager.GetString("NotValidIBAN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records No.
        /// </summary>
        public static string RecordsNo {
            get {
                return ResourceManager.GetString("RecordsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regenerate Request.
        /// </summary>
        public static string RegenerateRequest {
            get {
                return ResourceManager.GetString("RegenerateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject And Regenerate.
        /// </summary>
        public static string RejectAndRegenerateRequest {
            get {
                return ResourceManager.GetString("RejectAndRegenerateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string RejectedInPeriod {
            get {
                return ResourceManager.GetString("RejectedInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Only.
        /// </summary>
        public static string RejectOnlyRequest {
            get {
                return ResourceManager.GetString("RejectOnlyRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject And Regenerate.
        /// </summary>
        public static string RejectRequest {
            get {
                return ResourceManager.GetString("RejectRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reject Reason.
        /// </summary>
        public static string RequestDetails_RejectReason {
            get {
                return ResourceManager.GetString("RequestDetails_RejectReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Feedback.
        /// </summary>
        public static string RequestFeedback {
            get {
                return ResourceManager.GetString("RequestFeedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request rejected successfully.
        /// </summary>
        public static string RequestRejected {
            get {
                return ResourceManager.GetString("RequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Submitted Successfully.
        /// </summary>
        public static string RequestSentSuccefully {
            get {
                return ResourceManager.GetString("RequestSentSuccefully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Select &lt;b&gt;Rejected Students Only&lt;/b&gt; and submit the request..
        /// </summary>
        public static string Stipend_NotificationMessage_SelecteRejected {
            get {
                return ResourceManager.GetString("Stipend_NotificationMessage_SelecteRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Payment Method.
        /// </summary>
        public static string Stipend_PaymentMethod {
            get {
                return ResourceManager.GetString("Stipend_PaymentMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept Request.
        /// </summary>
        public static string Stipend_Title_AcceptRequest {
            get {
                return ResourceManager.GetString("Stipend_Title_AcceptRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Request.
        /// </summary>
        public static string Stipend_Title_CreateNewRequest {
            get {
                return ResourceManager.GetString("Stipend_Title_CreateNewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Request.
        /// </summary>
        public static string Stipend_Title_CreateRequest {
            get {
                return ResourceManager.GetString("Stipend_Title_CreateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Excluded Students.
        /// </summary>
        public static string Stipend_Title_ExcludedStudents {
            get {
                return ResourceManager.GetString("Stipend_Title_ExcludedStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Stipend Request.
        /// </summary>
        public static string Stipend_Title_NewRequest {
            get {
                return ResourceManager.GetString("Stipend_Title_NewRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string Stipend_Title_Periods {
            get {
                return ResourceManager.GetString("Stipend_Title_Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stipend Requests.
        /// </summary>
        public static string Stipend_Title_Requests {
            get {
                return ResourceManager.GetString("Stipend_Title_Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Stipends.
        /// </summary>
        public static string Stipend_Title_StudentRequests {
            get {
                return ResourceManager.GetString("Stipend_Title_StudentRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Stipends.
        /// </summary>
        public static string Stipend_Title_StudentStipends {
            get {
                return ResourceManager.GetString("Stipend_Title_StudentStipends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Request.
        /// </summary>
        public static string Stipend_Title_SubmitRequest {
            get {
                return ResourceManager.GetString("Stipend_Title_SubmitRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students In Request.
        /// </summary>
        public static string StipendRequestManagement_NoOfStudentInRequest {
            get {
                return ResourceManager.GetString("StipendRequestManagement_NoOfStudentInRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string StipendRequestManagement_NoOfStudentNew {
            get {
                return ResourceManager.GetString("StipendRequestManagement_NoOfStudentNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Of Students Has No Stipend.
        /// </summary>
        public static string StipendRequestManagement_NoOfStudentsHasNoStipend {
            get {
                return ResourceManager.GetString("StipendRequestManagement_NoOfStudentsHasNoStipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received.
        /// </summary>
        public static string StipendRequestManagement_NoOfStudentsHasStipend {
            get {
                return ResourceManager.GetString("StipendRequestManagement_NoOfStudentsHasStipend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pending.
        /// </summary>
        public static string StipendRequestManagement_NoOfStudentsPending {
            get {
                return ResourceManager.GetString("StipendRequestManagement_NoOfStudentsPending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rejected.
        /// </summary>
        public static string StipendRequestManagement_NoOfStudentsRejected {
            get {
                return ResourceManager.GetString("StipendRequestManagement_NoOfStudentsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students/Period.
        /// </summary>
        public static string StudentsInPeriod {
            get {
                return ResourceManager.GetString("StudentsInPeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students Rejected Successfully.
        /// </summary>
        public static string StudentsRejected {
            get {
                return ResourceManager.GetString("StudentsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stipend.
        /// </summary>
        public static string System_Header {
            get {
                return ResourceManager.GetString("System_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Type.
        /// </summary>
        public static string TermTypeId {
            get {
                return ResourceManager.GetString("TermTypeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To Day.
        /// </summary>
        public static string ToDay {
            get {
                return ResourceManager.GetString("ToDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Successfully.
        /// </summary>
        public static string TransferSuccessfully {
            get {
                return ResourceManager.GetString("TransferSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Processing Completed.
        /// </summary>
        public static string Upload_FileProcessingCompleted {
            get {
                return ResourceManager.GetString("Upload_FileProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Under Processing....
        /// </summary>
        public static string Upload_FileUnderProcessing {
            get {
                return ResourceManager.GetString("Upload_FileUnderProcessing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid &amp; Invalid Records Checking....
        /// </summary>
        public static string Upload_ValidAndInvalidRecordsChecking {
            get {
                return ResourceManager.GetString("Upload_ValidAndInvalidRecordsChecking", resourceCulture);
            }
        }
    }
}
