//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PortalResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PortalResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.Portal.PortalResources", typeof(PortalResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Announcements.
        /// </summary>
        public static string AnnouncementsAllLinkText {
            get {
                return ResourceManager.GetString("AnnouncementsAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Announcements.
        /// </summary>
        public static string AnnouncementsHeader {
            get {
                return ResourceManager.GetString("AnnouncementsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More.
        /// </summary>
        public static string AnnouncementsMoreLinkText {
            get {
                return ResourceManager.GetString("AnnouncementsMoreLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bulletins.
        /// </summary>
        public static string BullentinsHeader {
            get {
                return ResourceManager.GetString("BullentinsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All Bulletins.
        /// </summary>
        public static string BulletinsAllLinkText {
            get {
                return ResourceManager.GetString("BulletinsAllLinkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Announcements.
        /// </summary>
        public static string Url_AnnouncementsAllLink {
            get {
                return ResourceManager.GetString("Url_AnnouncementsAllLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Announcement/.
        /// </summary>
        public static string Url_AnnouncementsMoreLink {
            get {
                return ResourceManager.GetString("Url_AnnouncementsMoreLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /Home/Bulletins.
        /// </summary>
        public static string Url_BulletinsAllLink {
            get {
                return ResourceManager.GetString("Url_BulletinsAllLink", resourceCulture);
            }
        }
    }
}
