//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace COE.Common.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("COE.Common.Localization.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Data.
        /// </summary>
        public static string AcademicData_OSH {
            get {
                return ResourceManager.GetString("AcademicData_OSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School.
        /// </summary>
        public static string AcademicInformation {
            get {
                return ResourceManager.GetString("AcademicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your academic information.
        /// </summary>
        public static string AcademicInformations {
            get {
                return ResourceManager.GetString("AcademicInformations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Year.
        /// </summary>
        public static string AcademicYear {
            get {
                return ResourceManager.GetString("AcademicYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Un Defined.
        /// </summary>
        public static string AcademicYearTermUnDefined {
            get {
                return ResourceManager.GetString("AcademicYearTermUnDefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your account details.
        /// </summary>
        public static string AccountDetails {
            get {
                return ResourceManager.GetString("AccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievment.
        /// </summary>
        public static string Achievment {
            get {
                return ResourceManager.GetString("Achievment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your achievment.
        /// </summary>
        public static string AchievmentValidation {
            get {
                return ResourceManager.GetString("AchievmentValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ActionDelete {
            get {
                return ResourceManager.GetString("ActionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation Code.
        /// </summary>
        public static string ActivationCode {
            get {
                return ResourceManager.GetString("ActivationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicants.
        /// </summary>
        public static string Applicants {
            get {
                return ResourceManager.GetString("Applicants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Details.
        /// </summary>
        public static string ApplicationDetails {
            get {
                return ResourceManager.GetString("ApplicationDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, be sure to fill in the application correctly ..
        /// </summary>
        public static string ApplicationValidationError {
            get {
                return ResourceManager.GetString("ApplicationValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved.
        /// </summary>
        public static string Approved {
            get {
                return ResourceManager.GetString("Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associate Diploma.
        /// </summary>
        public static string AssociateDiploma {
            get {
                return ResourceManager.GetString("AssociateDiploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string AttachedFile {
            get {
                return ResourceManager.GetString("AttachedFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string AttachedFile1 {
            get {
                return ResourceManager.GetString("AttachedFile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment (Optional).
        /// </summary>
        public static string AttachedFile2 {
            get {
                return ResourceManager.GetString("AttachedFile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance.
        /// </summary>
        public static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attendance Attachment.
        /// </summary>
        public static string AttendanceAttachment {
            get {
                return ResourceManager.GetString("AttendanceAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can not submit transfer request befor {0} days of end-date of current academic term..
        /// </summary>
        public static string BeforeEndDateOfCurrentAcademicTerm {
            get {
                return ResourceManager.GetString("BeforeEndDateOfCurrentAcademicTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth Date.
        /// </summary>
        public static string BirthDate {
            get {
                return ResourceManager.GetString("BirthDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hijri Birth Date.
        /// </summary>
        public static string BirthDateHijri {
            get {
                return ResourceManager.GetString("BirthDateHijri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your Birth Date.
        /// </summary>
        public static string BirthDateValidation {
            get {
                return ResourceManager.GetString("BirthDateValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth year.
        /// </summary>
        public static string BirthYear {
            get {
                return ResourceManager.GetString("BirthYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, please check your national ID number and hijri year of birth ..
        /// </summary>
        public static string BirthYearAndNationalIdValidation {
            get {
                return ResourceManager.GetString("BirthYearAndNationalIdValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Birth year hijri.
        /// </summary>
        public static string BirthYearHijri {
            get {
                return ResourceManager.GetString("BirthYearHijri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Hijri year of birth consisting of 4 valid numbers only ..
        /// </summary>
        public static string BirthYearMaxLength {
            get {
                return ResourceManager.GetString("BirthYearMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the Hijri year of birth consisting of 4 valid numbers only ..
        /// </summary>
        public static string BirthYearMinLength {
            get {
                return ResourceManager.GetString("BirthYearMinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your Birth Year..
        /// </summary>
        public static string BirthYearValidation {
            get {
                return ResourceManager.GetString("BirthYearValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Education Qualifications.
        /// </summary>
        public static string CandidateAcademicInformation {
            get {
                return ResourceManager.GetString("CandidateAcademicInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application checklist attachments.
        /// </summary>
        public static string CandidateAttachments {
            get {
                return ResourceManager.GetString("CandidateAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate Information.
        /// </summary>
        public static string CandidateInformation {
            get {
                return ResourceManager.GetString("CandidateInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Candidate No.
        /// </summary>
        public static string CandidateNo {
            get {
                return ResourceManager.GetString("CandidateNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupational Health And Safety Certifications.
        /// </summary>
        public static string CandidateQulifications {
            get {
                return ResourceManager.GetString("CandidateQulifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Capstone.
        /// </summary>
        public static string Capstone {
            get {
                return ResourceManager.GetString("Capstone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CBT.
        /// </summary>
        public static string CBT {
            get {
                return ResourceManager.GetString("CBT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center Basic Details.
        /// </summary>
        public static string CenterBasicDetails {
            get {
                return ResourceManager.GetString("CenterBasicDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string CenterConfirmation {
            get {
                return ResourceManager.GetString("CenterConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string CenterSummary {
            get {
                return ResourceManager.GetString("CenterSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Name.
        /// </summary>
        public static string CertificateDonor {
            get {
                return ResourceManager.GetString("CertificateDonor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Title.
        /// </summary>
        public static string CertificateName {
            get {
                return ResourceManager.GetString("CertificateName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Contacts.
        /// </summary>
        public static string ChangeContact {
            get {
                return ResourceManager.GetString("ChangeContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Failed to change student contact information . Please try again.
        /// </summary>
        public static string ChangeContactFailed {
            get {
                return ResourceManager.GetString("ChangeContactFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student contact information was successfully changed.
        /// </summary>
        public static string ChangeContactSuccessfully {
            get {
                return ResourceManager.GetString("ChangeContactSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Failed to change student contact , Please fill in the required fields  ..
        /// </summary>
        public static string ChangeContactValidation {
            get {
                return ResourceManager.GetString("ChangeContactValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change selected student status.
        /// </summary>
        public static string ChangeSelectedStudentStatus {
            get {
                return ResourceManager.GetString("ChangeSelectedStudentStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Status.
        /// </summary>
        public static string ChangeStatus {
            get {
                return ResourceManager.GetString("ChangeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Students.
        /// </summary>
        public static string ChangeStatusRequestStudents {
            get {
                return ResourceManager.GetString("ChangeStatusRequestStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Candidate.
        /// </summary>
        public static string CheckCandidate {
            get {
                return ResourceManager.GetString("CheckCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Identity.
        /// </summary>
        public static string CheckStudent {
            get {
                return ResourceManager.GetString("CheckStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , you cannot submit an enrollment request . Please enter your verification code sent at your mobile.
        /// </summary>
        public static string CheckVerificationCode {
            get {
                return ResourceManager.GetString("CheckVerificationCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , you cannot submit an enrollment request . Please check you NationalId.
        /// </summary>
        public static string CheckYourNationalId {
            get {
                return ResourceManager.GetString("CheckYourNationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College.
        /// </summary>
        public static string College {
            get {
                return ResourceManager.GetString("College", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Training Center.
        /// </summary>
        public static string College_OSH {
            get {
                return ResourceManager.GetString("College_OSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institute.
        /// </summary>
        public static string College_SP {
            get {
                return ResourceManager.GetString("College_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Address.
        /// </summary>
        public static string CollegeAddress {
            get {
                return ResourceManager.GetString("CollegeAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string Completed {
            get {
                return ResourceManager.GetString("Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm your application.
        /// </summary>
        public static string ConfirmApplication {
            get {
                return ResourceManager.GetString("ConfirmApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Continue {
            get {
                return ResourceManager.GetString("Continue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الإستمرار والدفع.
        /// </summary>
        public static string ContinuePayment {
            get {
                return ResourceManager.GetString("ContinuePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Continue.
        /// </summary>
        public static string ContinueWizard {
            get {
                return ResourceManager.GetString("ContinueWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate Title.
        /// </summary>
        public static string CourseName {
            get {
                return ResourceManager.GetString("CourseName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current College.
        /// </summary>
        public static string CurrentCollege {
            get {
                return ResourceManager.GetString("CurrentCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dean Information.
        /// </summary>
        public static string DeanInfo {
            get {
                return ResourceManager.GetString("DeanInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decision.
        /// </summary>
        public static string Decision {
            get {
                return ResourceManager.GetString("Decision", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferral Request.
        /// </summary>
        public static string DeferralRequest {
            get {
                return ResourceManager.GetString("DeferralRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deferral Reasons.
        /// </summary>
        public static string DeferralRequestReasons {
            get {
                return ResourceManager.GetString("DeferralRequestReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aacademic year term.
        /// </summary>
        public static string DeferralRequestTrainingTrimester {
            get {
                return ResourceManager.GetString("DeferralRequestTrainingTrimester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth.
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description Arabic.
        /// </summary>
        public static string DescriptionAr {
            get {
                return ResourceManager.GetString("DescriptionAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description English.
        /// </summary>
        public static string DescriptionEn {
            get {
                return ResourceManager.GetString("DescriptionEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diploma.
        /// </summary>
        public static string Diploma {
            get {
                return ResourceManager.GetString("Diploma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dismiss Request.
        /// </summary>
        public static string DismissRequest {
            get {
                return ResourceManager.GetString("DismissRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons of Dismiss.
        /// </summary>
        public static string DismissRequestReasons {
            get {
                return ResourceManager.GetString("DismissRequestReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Request.
        /// </summary>
        public static string DroppedWithdrawRequest {
            get {
                return ResourceManager.GetString("DroppedWithdrawRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Application Desires.
        /// </summary>
        public static string EditApplicationDesires {
            get {
                return ResourceManager.GetString("EditApplicationDesires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch Editing.
        /// </summary>
        public static string EditBatch {
            get {
                return ResourceManager.GetString("EditBatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Degree.
        /// </summary>
        public static string EducationLevel {
            get {
                return ResourceManager.GetString("EducationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Details.
        /// </summary>
        public static string EnrollmentDetails {
            get {
                return ResourceManager.GetString("EnrollmentDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Failed in changing student status to {0} . Please try again.
        /// </summary>
        public static string EnrollmentFailed {
            get {
                return ResourceManager.GetString("EnrollmentFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment History.
        /// </summary>
        public static string EnrollmentHistory {
            get {
                return ResourceManager.GetString("EnrollmentHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Information.
        /// </summary>
        public static string EnrollmentInformation {
            get {
                return ResourceManager.GetString("EnrollmentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Request.
        /// </summary>
        public static string EnrollmentRequest {
            get {
                return ResourceManager.GetString("EnrollmentRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Enrollment Request.
        /// </summary>
        public static string EnrollmentRequestEdit {
            get {
                return ResourceManager.GetString("EnrollmentRequestEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Request Wizard.
        /// </summary>
        public static string EnrollmentRequestWizard {
            get {
                return ResourceManager.GetString("EnrollmentRequestWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students.
        /// </summary>
        public static string Enrollments {
            get {
                return ResourceManager.GetString("Enrollments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enrollment Statistic Request.
        /// </summary>
        public static string EnrollmentStatisticRequest {
            get {
                return ResourceManager.GetString("EnrollmentStatisticRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student status was changed to {0} successfully ..
        /// </summary>
        public static string EnrollmentSuccessfully {
            get {
                return ResourceManager.GetString("EnrollmentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eportfolio.
        /// </summary>
        public static string Eportfolio {
            get {
                return ResourceManager.GetString("Eportfolio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have some form errors. Please check below..
        /// </summary>
        public static string Errors {
            get {
                return ResourceManager.GetString("Errors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exams.
        /// </summary>
        public static string Exams {
            get {
                return ResourceManager.GetString("Exams", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Institution Name.
        /// </summary>
        public static string FacultyName {
            get {
                return ResourceManager.GetString("FacultyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Family Name.
        /// </summary>
        public static string FamilyNameAr {
            get {
                return ResourceManager.GetString("FamilyNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your Arabic Family  Name.
        /// </summary>
        public static string FamilyNameArValidation {
            get {
                return ResourceManager.GetString("FamilyNameArValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Family Name.
        /// </summary>
        public static string FamilyNameEn {
            get {
                return ResourceManager.GetString("FamilyNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your English Family  Name.
        /// </summary>
        public static string FamilyNameEnValidation {
            get {
                return ResourceManager.GetString("FamilyNameEnValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Father Name.
        /// </summary>
        public static string FatherNameAr {
            get {
                return ResourceManager.GetString("FatherNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your Arabic Father Name.
        /// </summary>
        public static string FatherNameArValidation {
            get {
                return ResourceManager.GetString("FatherNameArValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Father Name.
        /// </summary>
        public static string FatherNameEn {
            get {
                return ResourceManager.GetString("FatherNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your English Father Name.
        /// </summary>
        public static string FatherNameEnValidation {
            get {
                return ResourceManager.GetString("FatherNameEnValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female Colleges.
        /// </summary>
        public static string FemaleColleges {
            get {
                return ResourceManager.GetString("FemaleColleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Semester.
        /// </summary>
        public static string FirstAcademicYearTerm {
            get {
                return ResourceManager.GetString("FirstAcademicYearTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First College.
        /// </summary>
        public static string FirstCollege {
            get {
                return ResourceManager.GetString("FirstCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First College Is Required.
        /// </summary>
        public static string FirstCollegeIsRequired {
            get {
                return ResourceManager.GetString("FirstCollegeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your first college.
        /// </summary>
        public static string FirstCollegeValidation {
            get {
                return ResourceManager.GetString("FirstCollegeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic First Name.
        /// </summary>
        public static string FirstNameAr {
            get {
                return ResourceManager.GetString("FirstNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your Arabic First Name.
        /// </summary>
        public static string FirstNameArValidation {
            get {
                return ResourceManager.GetString("FirstNameArValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English First Name.
        /// </summary>
        public static string FirstNameEn {
            get {
                return ResourceManager.GetString("FirstNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your English First Name.
        /// </summary>
        public static string FirstNameEnValidation {
            get {
                return ResourceManager.GetString("FirstNameEnValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Specialization.
        /// </summary>
        public static string FirstSpecialization {
            get {
                return ResourceManager.GetString("FirstSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Specialization Is Required.
        /// </summary>
        public static string FirstSpecializationIsRequired {
            get {
                return ResourceManager.GetString("FirstSpecializationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your first specialization.
        /// </summary>
        public static string FirstSpecializationValidation {
            get {
                return ResourceManager.GetString("FirstSpecializationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foundation.
        /// </summary>
        public static string Foundation {
            get {
                return ResourceManager.GetString("Foundation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Four Semester.
        /// </summary>
        public static string FourthAcademicYearTerm {
            get {
                return ResourceManager.GetString("FourthAcademicYearTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name Arabic.
        /// </summary>
        public static string FullNameArabic {
            get {
                return ResourceManager.GetString("FullNameArabic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Name English.
        /// </summary>
        public static string FullNameEnglish {
            get {
                return ResourceManager.GetString("FullNameEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Level.
        /// </summary>
        public static string FundingLevelID {
            get {
                return ResourceManager.GetString("FundingLevelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Funding Specialization.
        /// </summary>
        public static string FundingSpecializationID {
            get {
                return ResourceManager.GetString("FundingSpecializationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string GenderFemale {
            get {
                return ResourceManager.GetString("GenderFemale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string GenderMale {
            get {
                return ResourceManager.GetString("GenderMale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GPA.
        /// </summary>
        public static string GPA {
            get {
                return ResourceManager.GetString("GPA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your GPA.
        /// </summary>
        public static string GPAValidation {
            get {
                return ResourceManager.GetString("GPAValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Date.
        /// </summary>
        public static string GraduationDate {
            get {
                return ResourceManager.GetString("GraduationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graduation Year.
        /// </summary>
        public static string GraduationYear {
            get {
                return ResourceManager.GetString("GraduationYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your graduation year.
        /// </summary>
        public static string GraduationYearValidation {
            get {
                return ResourceManager.GetString("GraduationYearValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arabic Grand Father Name.
        /// </summary>
        public static string GrandFatherNameAr {
            get {
                return ResourceManager.GetString("GrandFatherNameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your Arabic Grand Father Name.
        /// </summary>
        public static string GrandFatherNameArValidation {
            get {
                return ResourceManager.GetString("GrandFatherNameArValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English Grand Father Name.
        /// </summary>
        public static string GrandFatherNameEn {
            get {
                return ResourceManager.GetString("GrandFatherNameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your English Grand Father Name.
        /// </summary>
        public static string GrandFatherNameEnValidation {
            get {
                return ResourceManager.GetString("GrandFatherNameEnValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry you can&apos;t apply new enrollment request . may be you have inprogress request or you are already enrolled..
        /// </summary>
        public static string HaveInProgressRequestOrEnrolled {
            get {
                return ResourceManager.GetString("HaveInProgressRequestOrEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The student&apos;s enrollment status is not allowed to applay this request..
        /// </summary>
        public static string HaveUnAcceptedEnrolled {
            get {
                return ResourceManager.GetString("HaveUnAcceptedEnrolled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eg : .
        /// </summary>
        public static string HijriBirthDateSample {
            get {
                return ResourceManager.GetString("HijriBirthDateSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InActive.
        /// </summary>
        public static string InActive {
            get {
                return ResourceManager.GetString("InActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inbox.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In Progress.
        /// </summary>
        public static string InProgress {
            get {
                return ResourceManager.GetString("InProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to College Address.
        /// </summary>
        public static string InstituteAddress {
            get {
                return ResourceManager.GetString("InstituteAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputs must be matched with true or false ..
        /// </summary>
        public static string Invalid_Boolean {
            get {
                return ResourceManager.GetString("Invalid_Boolean", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid DateTime ..
        /// </summary>
        public static string Invalid_DateTime {
            get {
                return ResourceManager.GetString("Invalid_DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Decimal number ..
        /// </summary>
        public static string Invalid_Decimal {
            get {
                return ResourceManager.GetString("Invalid_Decimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid domain name ..
        /// </summary>
        public static string Invalid_Domain {
            get {
                return ResourceManager.GetString("Invalid_Domain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ..
        /// </summary>
        public static string Invalid_Email {
            get {
                return ResourceManager.GetString("Invalid_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file path ..
        /// </summary>
        public static string Invalid_FilePath {
            get {
                return ResourceManager.GetString("Invalid_FilePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The inputs must be matched with (jpg|JPG|jpeg|JPEG|png|PNG|docx|DOCX|doc|DOC|pdf|PDF) file extention ..
        /// </summary>
        public static string Invalid_FileUploadExtention {
            get {
                return ResourceManager.GetString("Invalid_FileUploadExtention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid host url ..
        /// </summary>
        public static string Invalid_Host {
            get {
                return ResourceManager.GetString("Invalid_Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid HTML text ..
        /// </summary>
        public static string Invalid_HTML {
            get {
                return ResourceManager.GetString("Invalid_HTML", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Integer number ..
        /// </summary>
        public static string Invalid_Integer {
            get {
                return ResourceManager.GetString("Invalid_Integer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid IP Address ..
        /// </summary>
        public static string Invalid_IpAddress {
            get {
                return ResourceManager.GetString("Invalid_IpAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Numeric digits ..
        /// </summary>
        public static string Invalid_Numeric {
            get {
                return ResourceManager.GetString("Invalid_Numeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid URL ..
        /// </summary>
        public static string Invalid_Url {
            get {
                return ResourceManager.GetString("Invalid_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Join Date.
        /// </summary>
        public static string JoinDate {
            get {
                return ResourceManager.GetString("JoinDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been to the Faculty of Excellence?.
        /// </summary>
        public static string JoinedBefore {
            get {
                return ResourceManager.GetString("JoinedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been joined to the training centers ?.
        /// </summary>
        public static string JoinedBefore_OSH {
            get {
                return ResourceManager.GetString("JoinedBefore_OSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever been joined to the institutes?.
        /// </summary>
        public static string JoinedBefore_SP {
            get {
                return ResourceManager.GetString("JoinedBefore_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string JoinedBeforeNo {
            get {
                return ResourceManager.GetString("JoinedBeforeNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string JoinedBeforeYes {
            get {
                return ResourceManager.GetString("JoinedBeforeYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joined Term.
        /// </summary>
        public static string JoinedTerm {
            get {
                return ResourceManager.GetString("JoinedTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Joining.
        /// </summary>
        public static string Joining {
            get {
                return ResourceManager.GetString("Joining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Level.
        /// </summary>
        public static string Level {
            get {
                return ResourceManager.GetString("Level", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Account Details.
        /// </summary>
        public static string LoginAccountDetails {
            get {
                return ResourceManager.GetString("LoginAccountDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attached File.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male Colleges.
        /// </summary>
        public static string MaleColleges {
            get {
                return ResourceManager.GetString("MaleColleges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is some missing information, please contact administrator.
        /// </summary>
        public static string MissingInfo {
            get {
                return ResourceManager.GetString("MissingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile Number.
        /// </summary>
        public static string MobileNumber {
            get {
                return ResourceManager.GetString("MobileNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you hear about colleges of excellence?.
        /// </summary>
        public static string Motivation {
            get {
                return ResourceManager.GetString("Motivation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you hear about training centers ?.
        /// </summary>
        public static string Motivation_OSH {
            get {
                return ResourceManager.GetString("Motivation_OSH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How did you hear about the institute?.
        /// </summary>
        public static string Motivation_SP {
            get {
                return ResourceManager.GetString("Motivation_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your motivation.
        /// </summary>
        public static string MotivationValidation {
            get {
                return ResourceManager.GetString("MotivationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My Profile.
        /// </summary>
        public static string MyProfile {
            get {
                return ResourceManager.GetString("MyProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string MyRequests {
            get {
                return ResourceManager.GetString("MyRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name Arabic.
        /// </summary>
        public static string NameAr {
            get {
                return ResourceManager.GetString("NameAr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name English.
        /// </summary>
        public static string NameEn {
            get {
                return ResourceManager.GetString("NameEn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NationalId.
        /// </summary>
        public static string NationalId {
            get {
                return ResourceManager.GetString("NationalId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your NationalId.
        /// </summary>
        public static string NationalIdValidation {
            get {
                return ResourceManager.GetString("NationalIdValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New College.
        /// </summary>
        public static string NewCollege {
            get {
                return ResourceManager.GetString("NewCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New College Identifier.
        /// </summary>
        public static string NewCollegeId {
            get {
                return ResourceManager.GetString("NewCollegeId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string NewSpecialization {
            get {
                return ResourceManager.GetString("NewSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Specialization Identifier.
        /// </summary>
        public static string NewSpecializationId {
            get {
                return ResourceManager.GetString("NewSpecializationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Approved.
        /// </summary>
        public static string NotApproved {
            get {
                return ResourceManager.GetString("NotApproved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sorry , you may be not term enrrolled or may be already defere all terms.
        /// </summary>
        public static string NotTermEnrrolledOrTermsDeffered {
            get {
                return ResourceManager.GetString("NotTermEnrrolledOrTermsDeffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Full Funding Trimester.
        /// </summary>
        public static string NumberOfFullFundingTrimester {
            get {
                return ResourceManager.GetString("NumberOfFullFundingTrimester", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Other {
            get {
                return ResourceManager.GetString("Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other Information.
        /// </summary>
        public static string OtherInformation {
            get {
                return ResourceManager.GetString("OtherInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string OtherTransferReasons {
            get {
                return ResourceManager.GetString("OtherTransferReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OverAll.
        /// </summary>
        public static string OverAll {
            get {
                return ResourceManager.GetString("OverAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student password successfully changed ..
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Failed to change student password , please try again.
        /// </summary>
        public static string PasswordChangedFailed {
            get {
                return ResourceManager.GetString("PasswordChangedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry , Failed to change student password , Please fill in the required fields..
        /// </summary>
        public static string PasswordChangedValidation {
            get {
                return ResourceManager.GetString("PasswordChangedValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage of attendance per month on course during the session.
        /// </summary>
        public static string PercentageOfAttendance {
            get {
                return ResourceManager.GetString("PercentageOfAttendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal info.
        /// </summary>
        public static string Personalinfo {
            get {
                return ResourceManager.GetString("Personalinfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide Your Personal information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority.
        /// </summary>
        public static string Priority {
            get {
                return ResourceManager.GetString("Priority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qiyas.
        /// </summary>
        public static string Qiyas {
            get {
                return ResourceManager.GetString("Qiyas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your Qiyas.
        /// </summary>
        public static string QiyasValidation {
            get {
                return ResourceManager.GetString("QiyasValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qualification Level.
        /// </summary>
        public static string QualificationLevel {
            get {
                return ResourceManager.GetString("QualificationLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة المؤهلات والدورات.
        /// </summary>
        public static string QualificationManagment {
            get {
                return ResourceManager.GetString("QualificationManagment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} value must be between {1} to {2}.
        /// </summary>
        public static string RangeValidator {
            get {
                return ResourceManager.GetString("RangeValidator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstate Request.
        /// </summary>
        public static string ReinstateRequest {
            get {
                return ResourceManager.GetString("ReinstateRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This request will create a new enrollment for the student on the current term once its approved..
        /// </summary>
        public static string ReinstateRequestMessage {
            get {
                return ResourceManager.GetString("ReinstateRequestMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string RequestAction {
            get {
                return ResourceManager.GetString("RequestAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action By.
        /// </summary>
        public static string RequestActionBy {
            get {
                return ResourceManager.GetString("RequestActionBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Date.
        /// </summary>
        public static string RequestActionDate {
            get {
                return ResourceManager.GetString("RequestActionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string RequestComment {
            get {
                return ResourceManager.GetString("RequestComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request desires details.
        /// </summary>
        public static string RequestDesiresDetails {
            get {
                return ResourceManager.GetString("RequestDesiresDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Details.
        /// </summary>
        public static string RequestDetails {
            get {
                return ResourceManager.GetString("RequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request History.
        /// </summary>
        public static string RequestHistory {
            get {
                return ResourceManager.GetString("RequestHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Information.
        /// </summary>
        public static string RequestInformation {
            get {
                return ResourceManager.GetString("RequestInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Number.
        /// </summary>
        public static string RequestNumber {
            get {
                return ResourceManager.GetString("RequestNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests.
        /// </summary>
        public static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stage.
        /// </summary>
        public static string RequestStage {
            get {
                return ResourceManager.GetString("RequestStage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request Status.
        /// </summary>
        public static string RequestStatus {
            get {
                return ResourceManager.GetString("RequestStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requests Types.
        /// </summary>
        public static string RequestsTypes {
            get {
                return ResourceManager.GetString("RequestsTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Re-type New Password.
        /// </summary>
        public static string ReTypeNewPassword {
            get {
                return ResourceManager.GetString("ReTypeNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save &amp; Continue.
        /// </summary>
        public static string SaveAndContinue {
            get {
                return ResourceManager.GetString("SaveAndContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save As Draft.
        /// </summary>
        public static string SaveDraft {
            get {
                return ResourceManager.GetString("SaveDraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string SchoolCity {
            get {
                return ResourceManager.GetString("SchoolCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your city or town.
        /// </summary>
        public static string SchoolCityValidation {
            get {
                return ResourceManager.GetString("SchoolCityValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Name.
        /// </summary>
        public static string SchoolName {
            get {
                return ResourceManager.GetString("SchoolName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Educational organization name.
        /// </summary>
        public static string SchoolName_SP {
            get {
                return ResourceManager.GetString("SchoolName_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your school name.
        /// </summary>
        public static string SchoolNameValidation {
            get {
                return ResourceManager.GetString("SchoolNameValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Region.
        /// </summary>
        public static string SchoolRegion {
            get {
                return ResourceManager.GetString("SchoolRegion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your school region.
        /// </summary>
        public static string SchoolRegionValidation {
            get {
                return ResourceManager.GetString("SchoolRegionValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to School Type.
        /// </summary>
        public static string SchoolType {
            get {
                return ResourceManager.GetString("SchoolType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic qualification type.
        /// </summary>
        public static string SchoolType_SP {
            get {
                return ResourceManager.GetString("SchoolType_SP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your school type.
        /// </summary>
        public static string SchoolTypeValidation {
            get {
                return ResourceManager.GetString("SchoolTypeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Score.
        /// </summary>
        public static string Score {
            get {
                return ResourceManager.GetString("Score", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Semester.
        /// </summary>
        public static string SecondAcademicYearTerm {
            get {
                return ResourceManager.GetString("SecondAcademicYearTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second College.
        /// </summary>
        public static string SecondCollege {
            get {
                return ResourceManager.GetString("SecondCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your second college.
        /// </summary>
        public static string SecondCollegeValidation {
            get {
                return ResourceManager.GetString("SecondCollegeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Specialization.
        /// </summary>
        public static string SecondSpecialization {
            get {
                return ResourceManager.GetString("SecondSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second Specialization Is Required.
        /// </summary>
        public static string SecondSpecializationIsRequired {
            get {
                return ResourceManager.GetString("SecondSpecializationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your second specialization.
        /// </summary>
        public static string SecondSpecializationValidation {
            get {
                return ResourceManager.GetString("SecondSpecializationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Back.
        /// </summary>
        public static string SentBackToCandidate {
            get {
                return ResourceManager.GetString("SentBackToCandidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, this service is currently not available..
        /// </summary>
        public static string ServiceCurrentlyNotAvailable {
            get {
                return ResourceManager.GetString("ServiceCurrentlyNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        public static string Settings_ApplicationId {
            get {
                return ResourceManager.GetString("Settings_ApplicationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activation.
        /// </summary>
        public static string Settings_IsActive {
            get {
                return ResourceManager.GetString("Settings_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key.
        /// </summary>
        public static string Settings_Key {
            get {
                return ResourceManager.GetString("Settings_Key", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Secure.
        /// </summary>
        public static string Settings_Secure {
            get {
                return ResourceManager.GetString("Settings_Secure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string Settings_Type {
            get {
                return ResourceManager.GetString("Settings_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value.
        /// </summary>
        public static string Settings_Value {
            get {
                return ResourceManager.GetString("Settings_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specialization.
        /// </summary>
        public static string Specialization {
            get {
                return ResourceManager.GetString("Specialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not repeat the same selection of specialization.
        /// </summary>
        public static string SpecializationNotDuplicated {
            get {
                return ResourceManager.GetString("SpecializationNotDuplicated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS Exam.
        /// </summary>
        public static string SSSExamID {
            get {
                return ResourceManager.GetString("SSSExamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SSS Exam Result.
        /// </summary>
        public static string SSSExamResult {
            get {
                return ResourceManager.GetString("SSSExamResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Information.
        /// </summary>
        public static string StaffInfo {
            get {
                return ResourceManager.GetString("StaffInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Step 1 of 5.
        /// </summary>
        public static string StepOneOfFive {
            get {
                return ResourceManager.GetString("StepOneOfFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The stipends will not be disbursed if the applicant  is an employee, and the applicant will bear the consequences of any incorrect information about the employment status.
        /// </summary>
        public static string StipendsWarning {
            get {
                return ResourceManager.GetString("StipendsWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actual Mark.
        /// </summary>
        public static string StudentActualMark {
            get {
                return ResourceManager.GetString("StudentActualMark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Programs.
        /// </summary>
        public static string StudentApplication {
            get {
                return ResourceManager.GetString("StudentApplication", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student&apos;s Comment.
        /// </summary>
        public static string StudentComment {
            get {
                return ResourceManager.GetString("StudentComment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your desires to choose colleges.
        /// </summary>
        public static string StudentDesires {
            get {
                return ResourceManager.GetString("StudentDesires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disability Request.
        /// </summary>
        public static string StudentDisabilityRequest {
            get {
                return ResourceManager.GetString("StudentDisabilityRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string StudentInformation {
            get {
                return ResourceManager.GetString("StudentInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student Name.
        /// </summary>
        public static string StudentName {
            get {
                return ResourceManager.GetString("StudentName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Students Information.
        /// </summary>
        public static string StudentsInfo {
            get {
                return ResourceManager.GetString("StudentsInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Study Start Date.
        /// </summary>
        public static string StudyStartDate {
            get {
                return ResourceManager.GetString("StudyStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pay and Submit.
        /// </summary>
        public static string SubmitAndPay {
            get {
                return ResourceManager.GetString("SubmitAndPay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your form validation is successful!.
        /// </summary>
        public static string SuccessfulValidation {
            get {
                return ResourceManager.GetString("SuccessfulValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term End Date.
        /// </summary>
        public static string TermEndDate {
            get {
                return ResourceManager.GetString("TermEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Academic Term.
        /// </summary>
        public static string TermName {
            get {
                return ResourceManager.GetString("TermName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term Start Date.
        /// </summary>
        public static string TermStartDate {
            get {
                return ResourceManager.GetString("TermStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        public static string TermType {
            get {
                return ResourceManager.GetString("TermType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Semester.
        /// </summary>
        public static string ThirdAcademicYearTerm {
            get {
                return ResourceManager.GetString("ThirdAcademicYearTerm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third College.
        /// </summary>
        public static string ThirdCollege {
            get {
                return ResourceManager.GetString("ThirdCollege", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your  third college.
        /// </summary>
        public static string ThirdCollegeValidation {
            get {
                return ResourceManager.GetString("ThirdCollegeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Specialization.
        /// </summary>
        public static string ThirdSpecialization {
            get {
                return ResourceManager.GetString("ThirdSpecialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third Specialization Is Required.
        /// </summary>
        public static string ThirdSpecializationIsRequired {
            get {
                return ResourceManager.GetString("ThirdSpecializationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your  third specialization.
        /// </summary>
        public static string ThirdSpecializationValidation {
            get {
                return ResourceManager.GetString("ThirdSpecializationValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfer Request.
        /// </summary>
        public static string TransferRequest {
            get {
                return ResourceManager.GetString("TransferRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reasons Of Transfer.
        /// </summary>
        public static string TransferRequestReasons {
            get {
                return ResourceManager.GetString("TransferRequestReasons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you a university graduate?.
        /// </summary>
        public static string UniversityGraduated {
            get {
                return ResourceManager.GetString("UniversityGraduated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string UniversityGraduatedNo {
            get {
                return ResourceManager.GetString("UniversityGraduatedNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string UniversityGraduatedYes {
            get {
                return ResourceManager.GetString("UniversityGraduatedYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update From Yakeen.
        /// </summary>
        public static string UpdateFromYakeen {
            get {
                return ResourceManager.GetString("UpdateFromYakeen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Request.
        /// </summary>
        public static string WithdrawRequest {
            get {
                return ResourceManager.GetString("WithdrawRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Withdraw Request Details.
        /// </summary>
        public static string WithdrawRequestDetails {
            get {
                return ResourceManager.GetString("WithdrawRequestDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WorkFlows.
        /// </summary>
        public static string WorkFlows {
            get {
                return ResourceManager.GetString("WorkFlows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Status.
        /// </summary>
        public static string WorkStatus {
            get {
                return ResourceManager.GetString("WorkStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Provide your work status.
        /// </summary>
        public static string WorkStatusValidation {
            get {
                return ResourceManager.GetString("WorkStatusValidation", resourceCulture);
            }
        }
    }
}
